# Generated by Django 2.1.1 on 2019-09-12 07:00

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.mixins
import iris_masters.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iris_masters', '0055_responsetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrisTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('description', models.CharField(max_length=40, unique=True, verbose_name='Description')),
                ('write_medium_catalan', models.TextField(blank=True, help_text='Template for write mediums in catalan', verbose_name='Write Medium (CA)')),
                ('write_medium_spanish', models.TextField(blank=True, help_text='Template for write mediums in spanish', verbose_name='Write Medium (ES)')),
                ('sms_medium_catalan', models.TextField(blank=True, help_text='Template for SMS mediums in catalan', verbose_name='SMS Medium (CA)')),
                ('sms_medium_spanish', models.TextField(blank=True, help_text='Template for SMS mediums in spanish', verbose_name='SMS Medium (ES)')),
            ],
            options={
                'abstract': False,
            },
            bases=(iris_masters.mixins.CleanSafeDeleteBase, models.Model),
        ),
        migrations.CreateModel(
            name='IrisTemplateRecordTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='Enabled')),
                ('iris_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_templates.IrisTemplate')),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_masters.RecordType')),
            ],
            options={
                'abstract': False,
            },
            bases=(iris_masters.mixins.CleanEnabledBase, models.Model),
        ),
        migrations.AddField(
            model_name='iristemplate',
            name='record_types',
            field=models.ManyToManyField(through='iris_templates.IrisTemplateRecordTypes', to='iris_masters.RecordType'),
        ),
        migrations.AddField(
            model_name='iristemplate',
            name='response_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iris_masters.ResponseType'),
        ),
    ]
