# Generated by Django 2.1.1 on 2020-01-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0053_auto_20191216_2053'),
        ('iris_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iristemplate',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Group'),
        ),
        migrations.AddField(
            model_name='iristemplate',
            name='label',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='iristemplate',
            name='response_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='iris_masters.ResponseType'),
        ),
    ]
