# Generated by Django 2.1.1 on 2020-01-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris_templates', '0002_auto_20200113_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iristemplate',
            name='label',
        ),
    ]
