# Generated by Django 2.1.1 on 2020-02-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_templates', '0003_remove_iristemplate_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='iristemplate',
            name='sms_medium_english',
            field=models.TextField(blank=True, help_text='Template for SMS mediums in spanish', verbose_name='SMS Medium (EN)'),
        ),
        migrations.AddField(
            model_name='iristemplate',
            name='write_medium_english',
            field=models.TextField(blank=True, help_text='Template for write mediums in spanish', verbose_name='Write Medium (EN)'),
        ),
    ]
