# Generated by Django 2.2 on 2021-11-22 13:41

from django.db import migrations
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_templates', '0004_auto_20200211_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iristemplate',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=36, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='iristemplaterecordtypes',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=36, verbose_name='User ID'),
        ),
    ]
