# Generated by Django 2.2 on 2022-02-01 09:20

from django.db import migrations
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_templates', '0005_auto_20211122_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iristemplate',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='iristemplaterecordtypes',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
    ]
