# Generated by Django 2.1.1 on 2019-07-02 08:32

from django.db import migrations, models
import iris_masters.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ariadna',
            fields=[
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('input_number', models.IntegerField(verbose_name='Input number')),
                ('digit_control', models.CharField(max_length=10, verbose_name='Digit control')),
                ('destination_num', models.CharField(max_length=10, verbose_name='Destination number')),
                ('input_office', models.CharField(max_length=10, verbose_name='Input office')),
                ('destination_office', models.CharField(max_length=10, verbose_name='Destination office')),
                ('destination_suboffice', models.CharField(max_length=10, verbose_name='Input suboffice')),
                ('presentation_date', models.CharField(max_length=50, verbose_name='Presentation date')),
                ('presentation_hour', models.CharField(max_length=10, verbose_name='Presentation hour')),
                ('applicant_type', models.CharField(max_length=10, verbose_name='Applicant type')),
                ('applicant_surnames', models.CharField(max_length=30, verbose_name='Applicant surnames')),
                ('applicant_name', models.CharField(max_length=15, verbose_name='Applicant name')),
                ('applicant_doc', models.CharField(max_length=10, verbose_name='Applicant doc')),
                ('applicant_doc_type', models.CharField(max_length=10, verbose_name='Applicant doc type')),
                ('interested_type', models.CharField(max_length=10, verbose_name='Interested type')),
                ('interested_surnames', models.CharField(max_length=30, verbose_name='Interested surnames')),
                ('interested_name', models.CharField(max_length=15, verbose_name='Input office')),
                ('interested_doc', models.CharField(max_length=10, verbose_name='Interested doc')),
                ('interested_doc_type', models.CharField(max_length=10, verbose_name='Interested doc type')),
                ('support_type', models.CharField(max_length=10, verbose_name='Support type')),
                ('matter_type', models.CharField(max_length=10, verbose_name='Matter type')),
                ('doc_type', models.CharField(max_length=10, verbose_name='Doc type')),
                ('doc_subtype', models.CharField(max_length=10, verbose_name='Doc subtype')),
                ('arbitri', models.CharField(max_length=10, verbose_name='Arbitri')),
                ('issue', models.CharField(max_length=200, verbose_name='Issue')),
                ('state', models.CharField(max_length=10, verbose_name='State')),
                ('destination_register', models.CharField(max_length=10, verbose_name='Destination register')),
                ('albara_number', models.IntegerField(verbose_name='Albara number')),
                ('ref_file', models.CharField(max_length=25, verbose_name='Referencial file')),
                ('certificate', models.CharField(max_length=15, verbose_name='Certificate')),
                ('user_created', models.CharField(max_length=10, verbose_name='User created')),
                ('user_updated', models.CharField(max_length=10, verbose_name='User updated')),
                ('date_state', models.CharField(max_length=10, verbose_name='Date state')),
                ('bill_num', models.CharField(max_length=10, verbose_name='Bill number')),
                ('bill_import', models.IntegerField(verbose_name='Bill import')),
                ('command_num', models.CharField(max_length=12, verbose_name='Command number')),
                ('command_contract', models.CharField(max_length=12, verbose_name='Command contract')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('used', models.BooleanField(default=True, verbose_name='Used')),
                ('date_us', models.DateTimeField(verbose_name='Date us')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ariadna',
            unique_together={('year', 'input_number')},
        ),
    ]
