# Generated by Django 2.1.1 on 2019-07-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariadna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ariadna',
            name='albara_number',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='applicant_doc_type',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='arbitri',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='bill_import',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='bill_num',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='command_contract',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='command_num',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='date_state',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='destination_num',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='destination_register',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='destination_suboffice',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='digit_control',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='doc_subtype',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='interested_doc',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='interested_doc_type',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='interested_name',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='interested_surnames',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='interested_type',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='presentation_hour',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='ref_file',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='state',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='support_type',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='ariadna',
            name='user_updated',
        ),
        migrations.AlterField(
            model_name='ariadna',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
