# Generated by Django 2.1.1 on 2019-07-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariadna', '0003_auto_20190710_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariadna',
            name='presentation_date',
            field=models.DateField(verbose_name='Presentation date'),
        ),
    ]
