# Generated by Django 2.1.1 on 2019-09-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariadna', '0006_auto_20190722_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariadna',
            name='applicant_doc_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'NIF'),
                                                            (1, 'NIE'),
                                                            (2, 'PASS')],
                                                   default=0,
                                                   verbose_name='Document Type'),
        ),
    ]
