# Generated by Django 2.1.1 on 2020-05-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariadna', '0007_ariadna_applicant_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariadna',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
