# Generated by Django 2.1.1 on 2020-09-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariadna', '0011_auto_20200914_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariadna',
            name='contact',
            field=models.CharField(blank=True, default='Ariadna', max_length=10, null=True, verbose_name='contact'),
        ),
    ]
