# Generated by Django 2.2 on 2021-11-22 13:41

from django.db import migrations
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('ariadna', '0013_auto_20210225_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariadna',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=36, verbose_name='User ID'),
        ),
    ]
