# Generated by Django 2.2 on 2022-02-01 09:45

from django.db import migrations
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('ariadna', '0014_auto_20211122_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ariadna',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
    ]
