# Generated by Django 2.1.1 on 2019-05-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('record_cards', '0052_auto_20190513_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRecordId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_code', models.CharField(max_length=60)),
                ('record_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                  to='record_cards.RecordCard')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='externalrecordid',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integrations.ExternalService'),
        ),
    ]
