# Generated by Django 2.1.1 on 2019-06-03 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('iris_masters', '0036_externalservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalrecordid',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iris_masters.ExternalService'),
        ),
        migrations.DeleteModel(
            name='ExternalService',
        ),
    ]
