# Generated by Django 2.1.1 on 2019-06-17 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20190603_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalrecordid',
            name='record_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='external_ids', to='record_cards.RecordCard'),
        ),
    ]
