# Generated by Django 2.1.1 on 2020-01-19 08:51

from django.db import migrations, models
import integrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_auto_20190617_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(db_index=True, max_length=4)),
                ('validated_at', models.DateTimeField(null=True)),
                ('file', models.FileField(blank=True, max_length=250, null=True,
                 upload_to=integrations.models.opendata_path, verbose_name='Record File')),
                ('sent_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
