# Generated by Django 2.1.1 on 2020-01-19 10:06

from django.db import migrations
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_batchfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchfile',
            name='validated_by',
            field=iris_masters.models.UserIdField(blank=True, default='', max_length=20, verbose_name='User ID'),
        ),
    ]
