# Generated by Django 2.1.1 on 2020-02-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0108_auto_20200127_1057'),
        ('integrations', '0005_batchfile_validated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiirisFilesExtractionDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('special_feature', models.CharField(blank=True, max_length=100)),
                ('file_assigned', models.IntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=102)),
                ('register_code', models.CharField(blank=True, max_length=12)),
                ('resolution_user', models.CharField(blank=True, max_length=20)),
                ('special_feature_id', models.CharField(blank=True, max_length=60)),
                ('reasigned_days', models.CharField(blank=True, max_length=10)),
                ('response_operator', models.CharField(blank=True, max_length=10)),
                ('claimed', models.BooleanField(default=False)),
                ('claimed_date', models.DateField(blank=True)),
                ('reasignation_response_operator', models.BooleanField(default=False)),
                ('files_fill', models.CharField(blank=True, max_length=13)),
                ('claimed_response_profile', models.BooleanField(default=False)),
                ('record_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 to='record_cards.RecordCard')),
            ],
        ),
        migrations.CreateModel(
            name='GpoHistoric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('indicator', models.CharField(blank=True, max_length=40)),
                ('month', models.CharField(blank=True, max_length=2)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('value', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GpoIndicators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('indicator', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('historic', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GpoSect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('district_sector_id', models.IntegerField()),
                ('identifier', models.CharField(blank=True, max_length=4)),
            ],
        ),
    ]
