# Generated by Django 2.1.1 on 2020-02-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_biirisfilesextractiondetail_gpohistoric_gpoindicators_gposect'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchfile',
            name='newest_date_limit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Newest date limit'),
        ),
        migrations.AddField(
            model_name='batchfile',
            name='oldest_date_limit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oldest date limit'),
        ),
    ]
