# Generated by Django 2.1.1 on 2020-05-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_auto_20200214_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('normalized_record_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('element', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
                ('created_day', models.CharField(max_length=100)),
                ('created_month', models.CharField(max_length=100)),
                ('created_year', models.CharField(max_length=100)),
                ('closing_day', models.CharField(max_length=100)),
                ('closing_month', models.CharField(max_length=100)),
                ('closing_year', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('neighborhood_id', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('research_zone', models.CharField(max_length=100)),
                ('via_type', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('street2', models.CharField(max_length=100)),
                ('xetrs89a', models.CharField(max_length=100)),
                ('yetrs89a', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('support', models.CharField(max_length=100)),
                ('response_channel', models.CharField(max_length=100)),
            ],
        ),
    ]
