# Generated by Django 2.1.1 on 2020-05-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_opendatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendatamodel',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
