# Generated by Django 2.1.1 on 2020-05-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_opendatamodel_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendatamodel',
            name='district_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
