# Generated by Django 2.1.1 on 2020-05-12 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_opendatamodel_district_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchfile',
            name='trimestre',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)],
                                      null=True, verbose_name='Trimestre'),
        ),
        migrations.AddField(
            model_name='batchfile',
            name='year',
            field=models.IntegerField(blank=True, null=True,
                                      validators=[django.core.validators.MinValueValidator(2000)],
                                      verbose_name='Year'),
        ),
    ]
