# Generated by Django 2.1.1 on 2020-06-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_auto_20200512_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchfile',
            name='status',
            field=models.IntegerField(choices=[('CREATED', 1), ('IN_VALIDATION', 2), ('VALIDATED', 3)], default=1),
        ),
    ]
