# Generated by Django 2.1.1 on 2021-04-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_batchfile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('record_response_data', models.IntegerField()),
                ('reason_id', models.IntegerField()),
                ('reason_desc', models.CharField(max_length=100)),
                ('record_type_id', models.IntegerField()),
                ('element_detail_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
                ('support_id', models.IntegerField()),
                ('id_applicant_type', models.IntegerField()),
                ('id_applicant', models.IntegerField()),
                ('id_citizen', models.IntegerField()),
                ('id_social', models.IntegerField()),
                ('id_ubication', models.IntegerField()),
                ('id_district', models.IntegerField()),
                ('barri_name', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('tipus_via', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('barri_id', models.IntegerField()),
                ('special_feature_value', models.CharField(max_length=100)),
                ('first_reas_date', models.DateTimeField()),
                ('reas_id', models.IntegerField()),
                ('first_result_group', models.IntegerField()),
                ('second_result_group', models.IntegerField()),
                ('research_zone', models.CharField(max_length=100)),
                ('statistical_sector', models.CharField(max_length=100)),
                ('response_channel_id', models.IntegerField()),
                ('ans_limit_date', models.DateTimeField()),
                ('responsible_profile_id', models.IntegerField()),
                ('user_id', models.CharField(max_length=100)),
                ('input_channel_id', models.IntegerField()),
                ('record_state_id', models.IntegerField()),
                ('geocode_district_id', models.IntegerField()),
                ('coordinate_x', models.IntegerField()),
                ('coordinate_y', models.IntegerField()),
                ('record_parent_claimed', models.CharField(max_length=100)),
                ('normalized_record_id', models.CharField(max_length=100)),
                ('claims_number', models.IntegerField()),
            ],
            options={
                'db_table': 'bi_aux',
                'managed': False,
            },
        ),
    ]
