# Generated by Django 2.1.1 on 2021-05-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_biview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendatamodel',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='street2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='xetrs89a',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='yetrs89a',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
