# Generated by Django 2.1.1 on 2021-05-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_auto_20210504_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendatamodel',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='closing_day',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='closing_month',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='closing_year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='created_day',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='created_month',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='created_year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='detail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='district_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='element',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='neighborhood',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='neighborhood_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='normalized_record_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='research_zone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='support',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opendatamodel',
            name='via_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
