# Generated by Django 2.2 on 2022-02-01 09:20

from django.db import migrations
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_auto_20211122_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchfile',
            name='validated_by',
            field=iris_masters.models.UserIdField(blank=True, default='', max_length=291, verbose_name='User ID'),
        ),
    ]
