# Generated by Django 2.1.1 on 2018-12-10 10:54

from django.db import migrations, models
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('description', models.CharField(max_length=40, verbose_name='Description')),
                ('description_es', models.CharField(max_length=40, null=True, verbose_name='Description')),
                ('description_ca', models.CharField(max_length=40, null=True, verbose_name='Description')),
                ('description_en', models.CharField(max_length=40, null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecisionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('description', models.CharField(max_length=40, verbose_name='Description')),
                ('description_es', models.CharField(max_length=40, null=True, verbose_name='Description')),
                ('description_ca', models.CharField(max_length=40, null=True, verbose_name='Description')),
                ('description_en', models.CharField(max_length=40, null=True, verbose_name='Description')),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('description_es', models.CharField(max_length=100, null=True, verbose_name='Description')),
                ('description_ca', models.CharField(max_length=100, null=True, verbose_name='Description')),
                ('description_en', models.CharField(max_length=100, null=True, verbose_name='Description')),
                ('reason_type', models.CharField(choices=[('r', 'Reassignment')], max_length=1, verbose_name='Reason type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
