# Generated by Django 2.1.1 on 2018-12-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0002_communicationmedia_decisiontype_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtype',
            name='description_ca',
            field=models.CharField(max_length=40, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='recordtype',
            name='description_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='recordtype',
            name='description_es',
            field=models.CharField(max_length=40, null=True, verbose_name='Description'),
        ),
    ]
