# Generated by Django 2.1.1 on 2019-01-03 12:05

from django.db import migrations, models
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0003_auto_20181212_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('parameter', models.CharField(max_length=60)),
                ('valor', models.TextField()),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=400)),
                ('original_description', models.TextField()),
                ('show', models.BooleanField(default=True)),
                ('data_type', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
