# Generated by Django 2.1.1 on 2019-01-03 16:20

from django.db import migrations, models
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0004_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('description', models.CharField(max_length=20, verbose_name='Description')),
                ('description_es', models.CharField(max_length=20, null=True, verbose_name='Description')),
                ('description_ca', models.CharField(max_length=20, null=True, verbose_name='Description')),
                ('description_en', models.CharField(max_length=20, null=True, verbose_name='Description')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
