# Generated by Django 2.1.1 on 2019-01-10 12:13

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0006_auto_20190109_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputChannelSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('input_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_masters.InputChannel')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('description', models.CharField(max_length=40, unique=True, verbose_name='Description')),
                ('description_es', models.CharField(max_length=40, null=True, unique=True, verbose_name='Description')),
                ('description_ca', models.CharField(max_length=40, null=True, unique=True, verbose_name='Description')),
                ('description_en', models.CharField(max_length=40, null=True, unique=True, verbose_name='Description')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('input_channels', models.ManyToManyField(blank=True, through='iris_masters.InputChannelSupport', to='iris_masters.InputChannel')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.DeleteModel(
            name='Suport',
        ),
        migrations.AddField(
            model_name='inputchannelsupport',
            name='support',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_masters.Support'),
        ),
        migrations.AlterUniqueTogether(
            name='inputchannelsupport',
            unique_together={('input_channel', 'support')},
        ),
    ]
