# Generated by Django 2.1.1 on 2019-01-11 15:59

from django.db import migrations, models
import django.utils.timezone
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0008_applicanttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputchannel',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='inputchannel',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputchannel',
            name='description_ca',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='inputchannel',
            name='description_en',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='inputchannel',
            name='description_es',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='inputchannel',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AddField(
            model_name='inputchannel',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='inputchannel',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Last update'),
        ),
        migrations.AddField(
            model_name='inputchannel',
            name='user_id',
            field=iris_masters.models.UserIdField(default='', max_length=20, verbose_name='User ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inputchannel',
            name='description',
            field=models.CharField(max_length=40, unique=True, verbose_name='Description'),
        ),
    ]
