# Generated by Django 2.1.1 on 2019-01-14 11:16

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0009_auto_20190111_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputChannelApplicantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('user_update_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('applicant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_masters.ApplicantType')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.RemoveField(
            model_name='support',
            name='input_channels',
        ),
        migrations.AddField(
            model_name='inputchannel',
            name='supports',
            field=models.ManyToManyField(blank=True, through='iris_masters.InputChannelSupport', to='iris_masters.Support'),
        ),
        migrations.AddField(
            model_name='inputchannelsupport',
            name='user_update_id',
            field=iris_masters.models.UserIdField(default=' ', max_length=20, verbose_name='User ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputchannelapplicanttype',
            name='input_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_masters.InputChannel'),
        ),
        migrations.AddField(
            model_name='inputchannel',
            name='applicant_types',
            field=models.ManyToManyField(blank=True, through='iris_masters.InputChannelApplicantType', to='iris_masters.ApplicantType'),
        ),
        migrations.AlterUniqueTogether(
            name='inputchannelapplicanttype',
            unique_together={('input_channel', 'applicant_type')},
        ),
    ]
