# Generated by Django 2.1.1 on 2019-01-23 12:48

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0010_auto_20190114_1216'),
        ('themes', '0021_auto_20190122_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('description', models.CharField(max_length=40, unique=True, verbose_name='Description')),
                ('description_es', models.CharField(max_length=40, null=True, unique=True, verbose_name='Description')),
                ('description_ca', models.CharField(max_length=40, null=True, unique=True, verbose_name='Description')),
                ('description_en', models.CharField(max_length=40, null=True, unique=True, verbose_name='Description')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecordState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('description', models.CharField(max_length=40, unique=True, verbose_name='Description')),
                ('description_es', models.CharField(max_length=40, null=True, unique=True, verbose_name='Description')),
                ('description_ca', models.CharField(max_length=40, null=True, unique=True, verbose_name='Description')),
                ('description_en', models.CharField(max_length=40, null=True, unique=True, verbose_name='Description')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResponseChannelSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('response_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_masters.ResponseChannel')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_masters.Support')),
            ],
        ),
        migrations.DeleteModel(
            name='ExternalApplication',
        ),
        migrations.AddField(
            model_name='communicationmedia',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AddField(
            model_name='communicationmedia',
            name='input_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iris_masters.InputChannel'),
        ),
        migrations.AlterField(
            model_name='communicationmedia',
            name='description',
            field=models.CharField(max_length=40, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='communicationmedia',
            name='description_ca',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='communicationmedia',
            name='description_en',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='communicationmedia',
            name='description_es',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='decisiontype',
            name='description',
            field=models.CharField(max_length=40, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='decisiontype',
            name='description_ca',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='decisiontype',
            name='description_en',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='decisiontype',
            name='description_es',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='description',
            field=models.CharField(max_length=40, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='description_ca',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='description_en',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='description_es',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='communicationmedia',
            name='media_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iris_masters.MediaType'),
        ),
        migrations.AddField(
            model_name='support',
            name='response_channels',
            field=models.ManyToManyField(blank=True, through='iris_masters.ResponseChannelSupport', to='iris_masters.ResponseChannel'),
        ),
        migrations.AlterUniqueTogether(
            name='responsechannelsupport',
            unique_together={('response_channel', 'support')},
        ),
    ]
