# Generated by Django 2.1.1 on 2019-01-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0011_auto_20190123_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordstate',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='recordstate',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='recordstate',
            name='description_es',
        ),
        migrations.AlterField(
            model_name='recordstate',
            name='description',
            field=models.CharField(choices=[('0', 'Pending to validate'), ('1', 'In planning'), ('2', 'In resolution'), ('3', 'Pending answer'), ('4', 'Closed'), ('5', 'Cancelled'), ('6', 'Not processed'), ('7', 'External processing')], max_length=2, unique=True, verbose_name='Description'),
        ),
    ]
