# Generated by Django 2.1.1 on 2019-01-24 14:45

from django.db import migrations, models
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0012_auto_20190128_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('title', models.CharField(max_length=50, verbose_name='Description')),
                ('description', models.CharField(max_length=280, verbose_name='Description')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('expiration_date', models.DateTimeField(blank=True, help_text='Expiration date', null=True)),
                ('xaloc', models.BooleanField(default=False, verbose_name='Xaloc')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
