# Generated by Django 2.1.1 on 2019-01-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0013_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.CharField(choices=[('0', 'Closed directly'), ('1', 'Direct External Processing'), ('500', 'Planning, Resolution, Response'), ('501', 'Resolution, Response'), ('502', 'Evaluation, Resolution, Response'), ('503', 'Response'), ('504', 'External Processing'), ('505', 'External Processing + Automatic Email'), ('506', 'Resolution, External Processing'), ('507', 'Resolution, External Processing + Automatic Email')], max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
