# Generated by Django 2.1.1 on 2019-01-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0014_auto_20190128_1200'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='responsechannelsupport',
            unique_together={('response_channel', 'support', 'enabled')},
        ),
    ]
