# Generated by Django 2.1.1 on 2019-01-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0015_auto_20190129_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordstate',
            name='description',
            field=models.CharField(max_length=40, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recordstate',
            name='id',
            field=models.PositiveIntegerField(choices=[(0, 'Pending to validate'), (1, 'In planning'), (2, 'In resolution'), (3, 'Pending answer'), (4, 'Closed'), (5, 'Cancelled'), (6, 'Not processed'), (7, 'External processing')], primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='recordstate',
            unique_together={('description', 'enabled')},
        ),
    ]
