# Generated by Django 2.1.1 on 2019-02-04 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iris_masters', '0016_auto_20190130_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Important'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='seen_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Seen by'),
        ),
    ]
