# Generated by Django 2.1.1 on 2019-02-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0017_auto_20190204_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
