# Generated by Django 2.1.1 on 2019-02-13 11:56

from django.db import migrations, models
import django.utils.timezone
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0019_auto_20190213_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsechannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsechannel',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AddField(
            model_name='responsechannel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update'),
        ),
        migrations.AddField(
            model_name='responsechannel',
            name='user_id',
            field=iris_masters.models.UserIdField(default=' ', max_length=20, verbose_name='User ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responsechannel',
            name='id',
            field=models.IntegerField(choices=[(0, 'Email'), (1, 'Sms'), (2, 'Letter'), (3, 'None'), (4, 'Immediate'), (5, 'Telephone')], primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
