# Generated by Django 2.1.1 on 2019-02-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0020_auto_20190213_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reason',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='reason',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='reason',
            name='description_es',
        ),
        migrations.AddField(
            model_name='reason',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='description',
            field=models.CharField(max_length=100, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='id',
            field=models.CharField(choices=[('-3', '-3'), ('19', '19'), ('16', '16'), ('17', '17'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('12', '12'), ('13', '13'), ('-2', '-2'), ('-1', '-1'), ('14', '14'), ('26', '26')], max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='reason_type',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='Reason type'),
        ),
    ]
