# Generated by Django 2.1.1 on 2019-03-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0022_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
