# Generated by Django 2.1.1 on 2019-03-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0023_auto_20190308_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicanttype',
            name='id',
            field=models.IntegerField(choices=[(20, 20), (18, 18), (4, 4), (0, 0), (13, 13), (15, 15), (6, 6), (1, 1), (9, 9), (10, 10), (2, 2), (3, 3), (16, 16), (17, 17), (5, 5), (11, 11), (7, 7), (8, 8), (12, 12), (21, 21), (14, 14), (23, 23), (24, 24), (25, 25), (100, 100)], primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
