# Generated by Django 2.1.1 on 2019-03-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0026_auto_20190313_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='allow_derivation',
            field=models.BooleanField(default=True, verbose_name='Allow derivation'),
        ),
    ]
