# Generated by Django 2.1.1 on 2019-03-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0027_district_allow_derivation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsechannel',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='responsechannel',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=100),
        ),
    ]
