# Generated by Django 2.1.1 on 2019-04-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0029_resolutiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description_hash',
            field=models.CharField(blank=True, max_length=100, verbose_name='Description hash'),
        ),
    ]
