# Generated by Django 2.1.1 on 2019-04-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0032_auto_20190409_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='allow_nd',
            field=models.BooleanField(default=False, verbose_name='Allow citizen ND'),
        ),
    ]
