# Generated by Django 2.1.1 on 2019-04-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0033_support_allow_nd'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inputchannel',
            unique_together={('description', 'enabled')},
        ),
    ]
