# Generated by Django 2.1.1 on 2019-05-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0034_auto_20190412_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='applicanttype',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='application',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='communicationmedia',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='inputchannel',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='inputchannelapplicanttype',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='inputchannelsupport',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='mediatype',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='show',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='reason',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='recordstate',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='resolutiontype',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='responsechannel',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='responsechannelsupport',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='support',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
    ]
