# Generated by Django 2.1.1 on 2019-06-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0035_auto_20190508_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_uid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
