# Generated by Django 2.1.1 on 2019-06-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0040_auto_20190617_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalservice',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
