# Generated by Django 2.1.1 on 2019-06-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0041_externalservice_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalservice',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
