# Generated by Django 2.1.1 on 2019-07-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0043_support_communication_media_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='register_required',
            field=models.BooleanField(default=False, verbose_name='Requires register code'),
        ),
    ]
