# Generated by Django 2.1.1 on 2019-07-22 12:38
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0044_support_register_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationmedia',
            name='enabled',
        ),
        migrations.AddField(
            model_name='communicationmedia',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.RemoveField(
            model_name='inputchannel',
            name='enabled',
        ),
        migrations.AddField(
            model_name='inputchannel',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.RemoveField(
            model_name='support',
            name='enabled',
        ),
        migrations.AddField(
            model_name='inputchannel',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='support',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.RemoveField(
            model_name='applicanttype',
            name='enabled',
        ),
        migrations.AddField(
            model_name='applicanttype',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='applicanttype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='reason',
            name='enabled',
        ),
        migrations.AddField(
            model_name='reason',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reason',
            name='reason_type',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, verbose_name='Reason type'),
        ),
        migrations.RemoveField(
            model_name='resolutiontype',
            name='enabled',
        ),
        migrations.AddField(
            model_name='resolutiontype',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='enabled',
        ),
        migrations.AddField(
            model_name='announcement',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='seen_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Seen by'),
        ),
    ]
