# Generated by Django 2.1.1 on 2019-07-24 15:32

from django.db import migrations, models
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0045_auto_20190722_1438'),
        ('record_cards', '0060_auto_20190724_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reason',
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Description')),
                ('description_es', models.CharField(max_length=100, null=True, unique=True, verbose_name='Description')),
                ('description_ca', models.CharField(max_length=100, null=True, unique=True, verbose_name='Description')),
                ('description_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='Description')),
                ('reason_type', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, verbose_name='Reason type')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
