# Generated by Django 2.1.1 on 2019-08-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0047_auto_20190807_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={},
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='category',
        ),
    ]
