# Generated by Django 2.1.1 on 2019-08-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0048_auto_20190826_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sign Up'), (1, 'Management'), (2, 'Support'), (3, 'Records'), (4, 'Web'), (5, 'Integrations'), (6, 'Reports')], default=0),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
