# Generated by Django 2.1.1 on 2019-09-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0052_auto_20190903_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolutiontype',
            name='can_claim_inside_ans',
            field=models.BooleanField(default=True),
        ),
    ]
