# Generated by Django 2.1.1 on 2019-09-05 11:05

from django.db import migrations


def set_can_claim_inside_ans(apps, schema_editor):
    ResolutionType = apps.get_model('iris_masters', 'ResolutionType')
    program_action_pk = 3  # program_action_pk resolution_type pk
    program_action, _ = ResolutionType.objects.get_or_create(pk=program_action_pk, defaults={
        'description': 'Es programa actuació', 'description_ca': 'Es programa actuació', 'description_es': None,
        'description_en': None, 'user_id': 'IRIS', 'order': 2, 'deleted': None, 'can_claim_inside_ans': False})
    program_action.can_claim_inside_ans = False
    program_action.save()


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0053_resolutiontype_can_claim_inside_ans'),
    ]

    operations = [
        migrations.RunPython(set_can_claim_inside_ans)
    ]
