# Generated by Django 2.1.1 on 2019-09-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0055_responsetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DecisionType',
        ),
        migrations.RemoveField(
            model_name='communicationmedia',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='communicationmedia',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='communicationmedia',
            name='description_es',
        ),
    ]
