# Generated by Django 2.1.1 on 2019-09-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0056_auto_20190912_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Others'), (7, 'Record card create'), (1, 'Management'), (2, 'Support'), (3, 'Records'), (4, 'Web'), (5, 'Integrations'), (6, 'Reports')], default=0),
        ),
    ]
