# Generated by Django 2.1.1 on 2019-09-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0057_auto_20190913_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordstate',
            name='acronym',
            field=models.CharField(blank=True, max_length=10, verbose_name='Acronym'),
        ),
    ]
