# Generated by Django 2.1.1 on 2019-10-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0058_recordstate_acronym'),
    ]

    # operations = [
    #      migrations.RunSQL("CREATE EXTENSION unaccent;")
    # ]
