# Generated by Django 2.1.1 on 2019-11-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0060_auto_20191030_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicanttype',
            name='send_response',
            field=models.BooleanField(default=True, verbose_name='Send Response'),
        ),
    ]
