# Generated by Django 2.1.1 on 2019-11-14 14:15

from django.db import migrations, models
import iris_masters.models


def create_default_templates(apps, *args, **kwargs):
    LetterTemplate = apps.get_model('iris_masters.LetterTemplate')
    Group = apps.get_model('profiles.Group')
    template_ids = Group.objects.values_list('letter_template_id').distinct()
    for tid in template_ids:
        if tid[0] is not None:
            LetterTemplate.objects.get_or_create(id=int(tid[0]), defaults={
                'description': 'Empty letter {}'.format(tid[0]), 'order': 0, 'enabled': True
            })


def noop(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0061_applicanttype_send_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('description', models.CharField(max_length=40, unique=True, verbose_name='Description')),
                ('name', models.CharField(max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_default_templates, noop)
    ]
