# Generated by Django 2.1.1 on 2019-11-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0062_lettertemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='description',
            field=models.CharField(max_length=100, unique=True, verbose_name='Description'),
        ),
    ]
