# Generated by Django 2.1.1 on 2019-11-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0064_auto_20191115_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurniturePickUp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('street_code', models.CharField(max_length=20, verbose_name='Street Code')),
                ('number', models.CharField(max_length=15, verbose_name='Number')),
                ('service_type', models.CharField(max_length=1, verbose_name='Service type')),
                ('service_description', models.CharField(blank=True, max_length=25, verbose_name='Service description')),
                ('enterprise_name', models.CharField(blank=True, max_length=40, verbose_name='Enterprise name')),
            ],
        ),
    ]
