# Generated by Django 2.1.1 on 2019-12-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0067_auto_20191211_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordstate',
            name='id',
            field=models.PositiveIntegerField(choices=[(0, 'Pending to validate'), (1, 'In planning'), (2, 'In resolution'), (3, 'Pending answer'), (4, 'Closed'), (5, 'Cancelled'), (6, 'Not processed'), (7, 'External processing'), (8, 'External returned'), (9, "Won't be done")], primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
