# Generated by Django 2.1.1 on 2019-12-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0068_auto_20191214_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputchannel',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='inputchannel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='inputchannel',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='support',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='support',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='support',
            name='description_es',
        ),
    ]
