# Generated by Django 2.1.1 on 2020-01-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0069_auto_20191224_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resolutiontype',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='applicanttype',
            name='description',
            field=models.CharField(max_length=40, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='applicanttype',
            name='description_ca',
            field=models.CharField(max_length=40, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='applicanttype',
            name='description_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='applicanttype',
            name='description_es',
            field=models.CharField(max_length=40, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='communicationmedia',
            name='description',
            field=models.CharField(max_length=40, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='inputchannel',
            name='description',
            field=models.CharField(max_length=40, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='description_ca',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='description_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='description_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resolutiontype',
            name='description',
            field=models.CharField(max_length=40, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resolutiontype',
            name='description_ca',
            field=models.CharField(max_length=40, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resolutiontype',
            name='description_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resolutiontype',
            name='description_es',
            field=models.CharField(max_length=40, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='responsetype',
            name='description',
            field=models.CharField(max_length=60, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='support',
            name='description',
            field=models.CharField(max_length=40, verbose_name='Description'),
        ),
        migrations.AlterUniqueTogether(
            name='applicanttype',
            unique_together={('description', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='communicationmedia',
            unique_together={('description', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='inputchannel',
            unique_together={('description', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='reason',
            unique_together={('description', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='resolutiontype',
            unique_together={('description', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='responsetype',
            unique_together={('description', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='support',
            unique_together={('description', 'deleted')},
        ),
    ]
