# Generated by Django 2.1.1 on 2020-02-21 14:09

from django.db import migrations


def delete_notramit_state(apps, schema_editor):
    NO_TRAMIT = 9
    NO_PROCESSED = 6
    Message = apps.get_model("communications", "Message")
    delete_notramit(Message, {"record_state_id": NO_TRAMIT}, {"record_state_id": NO_PROCESSED})
    RecordCard = apps.get_model("record_cards", "RecordCard")
    delete_notramit(RecordCard, {"record_state_id": NO_TRAMIT}, {"record_state_id": NO_PROCESSED})
    RecordCardStateHistory = apps.get_model("record_cards", "RecordCardStateHistory")
    delete_notramit(RecordCardStateHistory, {"previous_state_id": NO_TRAMIT}, {"previous_state_id": NO_PROCESSED})
    delete_notramit(RecordCardStateHistory, {"next_state_id": NO_TRAMIT}, {"next_state_id": NO_PROCESSED})
    RecordCardHistory = apps.get_model("record_cards", "RecordCardHistory")
    delete_notramit(RecordCardHistory, {"record_state_id": NO_TRAMIT}, {"record_state_id": NO_PROCESSED})
    Workflow = apps.get_model("record_cards", "Workflow")
    delete_notramit(Workflow, {"state_id": NO_TRAMIT}, {"state_id": NO_PROCESSED})
    DerivationDirect = apps.get_model("themes", "DerivationDirect")
    delete_notramit(DerivationDirect, {"record_state_id": NO_TRAMIT}, {"record_state_id": NO_PROCESSED})
    DerivationDistrict = apps.get_model("themes", "DerivationDistrict")
    delete_notramit(DerivationDistrict, {"record_state_id": NO_TRAMIT}, {"record_state_id": NO_PROCESSED})
    DerivationPolygon = apps.get_model("themes", "DerivationDistrict")
    delete_notramit(DerivationPolygon, {"record_state_id": NO_TRAMIT}, {"record_state_id": NO_PROCESSED})


def delete_notramit(model, filter_kwags, update_kwargs):
    model.objects.filter(**filter_kwags).update(**update_kwargs)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0071_auto_20200122_1203'),
    ]

    operations = [
        migrations.RunPython(delete_notramit_state, noop),
    ]
