# Generated by Django 2.1.1 on 2020-03-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0074_auto_20200225_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordstate',
            name='description_ca',
            field=models.CharField(max_length=40, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='recordstate',
            name='description_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='recordstate',
            name='description_es',
            field=models.CharField(max_length=40, null=True, verbose_name='Description'),
        ),
    ]
