# Generated by Django 2.2 on 2021-11-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0076_auto_20200414_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictSector',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('dist_sect_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('flag_ds', models.IntegerField(default=0)),
                ('discharge_date', models.DateTimeField()),
                ('user_id', models.CharField(max_length=20)),
                ('fl_authorized', models.IntegerField(default=0)),
                ('list_description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
