# Generated by Django 2.2 on 2022-01-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0078_auto_20211122_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='description_ca',
            new_name='description_gl',
        ),
        migrations.RenameField(
            model_name='mediatype',
            old_name='description_ca',
            new_name='description_gl',
        ),
        migrations.RenameField(
            model_name='recordstate',
            old_name='description_ca',
            new_name='description_gl',
        ),
        migrations.RenameField(
            model_name='recordtype',
            old_name='description_ca',
            new_name='description_gl',
        ),
    ]
