# Generated by Django 2.2 on 2022-02-01 09:20

from django.db import migrations
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0079_auto_20220124_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='applicanttype',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='communicationmedia',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='inputchannel',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='inputchannelapplicanttype',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='inputchannelapplicanttype',
            name='user_update_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='inputchannelsupport',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='inputchannelsupport',
            name='user_update_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='lettertemplate',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='mediatype',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='recordstate',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='recordtype',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='resolutiontype',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='responsechannel',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='responsechannelsupport',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='responsetype',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='support',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
    ]
