# Generated by Django 2.1.1 on 2019-06-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocols',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('protocol_id', models.CharField(max_length=30, verbose_name='Protocol id')),
                ('description', models.CharField(max_length=400, verbose_name='Description')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='protocols',
            unique_together={('protocol_id', 'enabled')},
        ),
    ]
