# Generated by Django 2.1.1 on 2019-07-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0002_protocols_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocols',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
