# Generated by Django 2.1.1 on 2019-07-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0003_auto_20190703_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocols',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
