# Generated by Django 2.1.1 on 2019-07-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0004_auto_20190704_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocols',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
