# Generated by Django 2.1.1 on 2020-01-17 10:23

from django.db import migrations
from django.utils import timezone


def protocols_deleted(apps, schema_editor):
    # We can"t import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Protocols = apps.get_model("protocols", "Protocols")
    for protocol in Protocols.objects.all():
        if not protocol.enabled:
            protocol.deleted = timezone.now()
            protocol.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('protocols', '0007_auto_20200117_1115'),
    ]

    operations = [
        migrations.RunPython(protocols_deleted, noop),
    ]
