# Generated by Django 2.1.1 on 2020-01-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0008_auto_20200117_1123'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='protocols',
            unique_together={('protocol_id', 'deleted')},
        ),
        migrations.RemoveField(
            model_name='protocols',
            name='enabled',
        ),
    ]
