from django.utils import timezone

from iris_masters.models import Reason
from datetime import datetime


def check_reasons(sender, **kwargs):
    reason_data = {
        Reason.CITIZEN_RESPONSE: {"desc": "Respuesta del ciudadano", "date": datetime(2012, 1, 31),
                                  "deleted": timezone.now(), "user_id": "IRIS", "reason_type": Reason.TYPE_0},
        Reason.THEME_CHANGE: {"desc": "Reasignación por cconio en clasificación temática",
                              "date": datetime(2011, 4, 29), "deleted": None, "user_id": "IRIS",
                              "reason_type": Reason.TYPE_3},
        Reason.RECORD_REOPEN: {"desc": "Anulación por reaportura de ficha", "date": datetime(2010, 3, 3),
                               "deleted": timezone.now(), "user_id": "IRIS", "reason_type": Reason.TYPE_1},
        Reason.EXPIRATION: {"desc": "Anulación por caducidad", "date": datetime(2010, 3, 22), "deleted": None,
                            "user_id": "IRIS", "reason_type": Reason.TYPE_1},
        Reason.FALSE_ERRONEOUS_DATA: {"desc": "Anulación por datos falsos o erróneos", "date": datetime(2005, 3, 22),
                                      "deleted": None, "user_id": "IRIS", "reason_type": Reason.TYPE_1},
        Reason.DUPLICITY_REPETITION: {"desc": "Anulación por duplicidad o reiteración", "date": datetime(2005, 3, 22),
                                      "deleted": None, "user_id": "IRIS", "reason_type": Reason.TYPE_1},
        Reason.DISRECPECTFUL_UNINTELLIGIBLE: {"desc": "Anulación por contenido irrespetuoso o ininteligible",
                                              "date": datetime(2005, 3, 22), "deleted": None, "user_id": "IRIS",
                                              "reason_type": Reason.TYPE_1},
        Reason.THEME_MISTAKE: {"desc": "Reasignación por error en clasificación temática",
                               "date": datetime(2005, 3, 22), "deleted": None, "user_id": "IRIS",
                               "reason_type": Reason.TYPE_2},
        Reason.COMPUTATIONS_CHANGE: {"desc": "Reasignación por cconio en les competencias",
                                     "date": datetime(2005, 3, 22), "deleted": None, "user_id": "IRIS",
                                     "reason_type": Reason.TYPE_2},
        Reason.COMPUTATIONS_OTHER_ADMIN: {"desc": "Reasignación por competencia de otra administración",
                                          "date": datetime(2005, 3, 22), "deleted": timezone.now(),
                                          "user_id": "IRIS", "reason_type": Reason.TYPE_2},
        Reason.CITIZEN_REQUEST: {"desc": "Petición del ciudadano", "date": datetime(2005, 4, 18), "deleted": None,
                                 "user_id": "IRIS", "reason_type": Reason.TYPE_1},
        Reason.INTERNAL_TRANSFER: {"desc": "Traspaso entre departamentos del mismo sector/districte/institut",
                                   "date": datetime(2005, 4, 22), "deleted": None,
                                   "user_id": "IRIS", "reason_type": Reason.TYPE_2},
        Reason.BUNKS_NO_ANSWER: {"desc": "Bitacolas. No requiere respuesta.", "date": datetime(2005, 5, 19),
                                 "deleted": timezone.now(), "user_id": "IRIS", "reason_type": Reason.TYPE_1},
        Reason.PAINTED_PRIVATE_SECTOR: {"desc": "Pintadas: competencia del sector privado",
                                        "date": datetime(2005, 5, 25), "deleted": timezone.now(), "user_id": "IRIS",
                                        "reason_type": Reason.TYPE_1},
        Reason.NOT_APPLICABLE: {"desc": "La actuación ya no se puede realizar o no procede",
                                "date": datetime(2005, 6, 2), "deleted": None, "user_id": "IRIS",
                                "reason_type": Reason.TYPE_1},
        Reason.COORDINATOR_EVALUATION: {"desc": "Valoración de la competencia por parte del Coordinador",
                                        "date": datetime(2009, 11, 4), "deleted": None, "user_id": "IRIS",
                                        "reason_type": Reason.TYPE_2},
        Reason.REASSIGNMENT_OTHER_ADMINS: {"desc": "Reasignación por competencia de otras Administraciones",
                                           "date": datetime(2009, 11, 4), "deleted": None, "user_id": "IRIS",
                                           "reason_type": Reason.TYPE_2},
        Reason.OBSERVATION: {"desc": "Observación", "date": datetime(2010, 1, 15), "deleted": timezone.now(),
                             "user_id": "IRIS", "reason_type": Reason.TYPE_2},
        Reason.CITIZEN_COMUNICATION: {"desc": "Comunicación con el ciudadano", "date": datetime(2009, 10, 8),
                                      "deleted": timezone.now(), "user_id": "IRIS", "reason_type": Reason.TYPE_0},
        Reason.BREAKE_DOWN_MULTI: {"desc": "Por desglosar en multiqueja", "date": datetime(2009, 11, 5),
                                   "deleted": None, "user_id": "IRIS", "reason_type": Reason.TYPE_2},
        Reason.VALIDATION_BY_ERROR: {"desc": "Anulación por validación por error", "date": datetime(2012, 5, 29),
                                     "deleted": None, "user_id": "IRIS", "reason_type": Reason.TYPE_1},

        Reason.RECORDCARD_URGENCY_CHANGE: {"desc": "Cambio urgente/no urgente", "date": datetime(2019, 3, 12),
                                           "deleted": None, "user_id": "IRIS", "reason_type": Reason.TYPE_4},
        Reason.RECORDCARD_BLOCK_CHANGE: {"desc": "Bloqueo/desbloqueo", "date": datetime(2019, 3, 12),
                                         "deleted": None, "user_id": "IRIS", "reason_type": Reason.TYPE_4},
        Reason.RECORDCARD_EXTERNAL_RETURN: {"desc": "Devolución tramitación externa", "date": datetime(2019, 3, 12),
                                            "deleted": None, "user_id": "IRIS", "reason_type": Reason.TYPE_4},
        Reason.RECORDCARD_EXTERNAL_CANCEL: {"desc": "Cancelación en tramitación externa", "date": datetime(2019, 3, 12),
                                            "deleted": None, "user_id": "IRIS", "reason_type": Reason.TYPE_4},
        Reason.RECORDCARD_EXTERNAL_CLOSE: {"desc": "Cierre en tramitación extern", "date": datetime(2019, 3, 12),
                                           "deleted": None, "user_id": "IRIS", "reason_type": Reason.TYPE_4},
        Reason.FEATURES_THEME_NO_VISIBLES: {"desc": "Características no visibles por cambio de temática",
                                            "date": datetime(2019, 3, 12), "deleted": None, "user_id": "IRIS",
                                            "reason_type": Reason.TYPE_4},
        Reason.GROUP_DELETED: {"desc": "Se ha eliminado el grupo que tenía asignada la ficha",
                               "date": datetime(2019, 3, 12), "deleted": None, "user_id": "IRIS",
                               "reason_type": Reason.TYPE_4},
        Reason.RECORDFILE_DELETED: {"desc": "Se ha eliminado un fichero asociado a una ficha",
                                    "date": datetime(2019, 3, 12), "deleted": None, "user_id": "IRIS",
                                    "reason_type": Reason.TYPE_4},
        Reason.RECORDCARD_UPDATED: {"desc": "Se ha modificado la ficha",
                                    "date": datetime(2019, 3, 12), "deleted": None, "user_id": "IRIS",
                                    "reason_type": Reason.TYPE_4},
        Reason.RECORDCARD_NO_ANSWER: {"desc": "No recibirá respuesta",
                                      "date": datetime(2019, 3, 12), "deleted": None, "user_id": "IRIS",
                                      "reason_type": Reason.TYPE_4},
        Reason.RECORDCARD_TWITTER: {"desc": "Twitter",
                                    "date": datetime(2019, 3, 12), "deleted": None, "user_id": "IRIS",
                                    "reason_type": Reason.TYPE_4},
        Reason.RECORDCARD_CANCEL_REQUEST: {"desc": "Se ha solicitado la anulación",
                                           "date": datetime(2019, 3, 12), "deleted": None, "user_id": "IRIS",
                                           "reason_type": Reason.TYPE_4},
        Reason.NO_IRIS: {"desc": "Tema municipal no gestionado desde IRIS",
                         "date": datetime(2012, 3, 19), "deleted": None, "user_id": "IRIS",
                         "reason_type": Reason.TYPE_2},
        Reason.REASSIGNMENT_UNEXPLAINED: {"desc": "Reasignación no argumentada",
                                          "date": datetime(2012, 3, 19), "deleted": None, "user_id": "IRIS",
                                          "reason_type": Reason.TYPE_2},
        Reason.INCORRECT_REASIGNATION: {"desc": "Reasignación errónea entre operadores",
                                        "date": datetime(2012, 3, 19), "deleted": None, "user_id": "IRIS",
                                        "reason_type": Reason.TYPE_2},
        Reason.DAIR_CORRECTION: {"desc": "Correción efectuada por el Administrador",
                                 "date": datetime(2012, 3, 19), "deleted": None, "user_id": "IRIS",
                                 "reason_type": Reason.TYPE_2},
        Reason.RECORDCARD_AUTOMATICALLY_CLOSED: {"desc": u"Ficha cerrada automáticament",
                                                 "date": datetime(2019, 3, 12), "deleted": None, "user_id": "IRIS",
                                                 "reason_type": Reason.TYPE_4},
        Reason.RECORDFILE_COPIED: {"desc": u"Fichero copiado a la ficha", "date": datetime(2019, 3, 12), "deleted": None,
                                   "user_id": "IRIS", "reason_type": Reason.TYPE_4},
        Reason.DERIVATE_RESIGNATION: {"desc": u"Reasignado por derivación", "date": datetime(2019, 3, 12),
                                      "deleted": None, "user_id": "IRIS", "reason_type": Reason.TYPE_4},
        Reason.INITIAL_ASSIGNATION: {"desc": u"Derivación inicial", "date": datetime(2019, 3, 12),
                                     "deleted": None, "user_id": "IRIS", "reason_type": Reason.TYPE_4},
        Reason.COPY_FILES: {"desc": u"Copiando fitxers", "date": datetime(2019, 3, 12),
                            "deleted": None, "user_id": "IRIS", "reason_type": Reason.TYPE_4},
        Reason.THEME_DELETED: {"desc": u"Temàtica borrada", "date": datetime(2019, 3, 12), "deleted": None,
                               "user_id": "IRIS", "reason_type": Reason.TYPE_4},
        Reason.RECORDCARD_RESEND_ANSWER: {"desc": u"Reenviar respuesta ficha", "date": datetime(2019, 3, 12),
                                          "deleted": None, "user_id": "IRIS", "reason_type": Reason.TYPE_4},
        Reason.RECORDCARD_INVALID_MAIL: {"desc": u"Correu electrónico no válido", "date": datetime(2019, 3, 12),
                                         "deleted": None, "user_id": "IRIS", "reason_type": Reason.TYPE_4},
        Reason.CLAIM_CITIZEN_REQUEST: {"desc": "Reclamación ciudadano", "date": datetime(2005, 4, 18), "deleted": None,
                                       "user_id": "IRIS", "reason_type": Reason.TYPE_4},
    }

    for reason_id, reason in reason_data.items():
        try:
            db_reason = Reason.all_objects.get(id=reason_id)
        except Reason.DoesNotExist:
            db_reason = Reason.all_objects.create(id=reason_id, description=reason["desc"], created_at=reason["date"],
                                                  deleted=reason["deleted"], user_id=reason["user_id"],
                                                  reason_type=reason["reason_type"])

        if db_reason.reason_type != reason["reason_type"]:
            db_reason.reason_type = reason["reason_type"]
            db_reason.save()

        if db_reason.deleted and not reason["deleted"]:
            Reason.all_objects.filter(pk=db_reason.pk).update(deleted=None)

        if reason["deleted"] and not db_reason.deleted:
            db_reason.delete()
