# Generated by Django 2.1.1 on 2018-11-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementdetail',
            old_name='element_code',
            new_name='detail_code',
        ),
        migrations.AddField(
            model_name='area',
            name='icon_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Icon Name'),
        ),
        migrations.AlterField(
            model_name='area',
            name='query_area',
            field=models.BooleanField(default=False, verbose_name='Query tree Area'),
        ),
        migrations.AlterField(
            model_name='element',
            name='icon_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Icon Name'),
        ),
    ]
