# Generated by Django 2.1.1 on 2018-11-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0004_auto_20181115_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementdetail',
            name='name',
            field=models.CharField(help_text='Detail description in Catalan.', max_length=90),
        ),
    ]
