# Generated by Django 2.1.1 on 2018-12-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0005_auto_20181119_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='themegroup',
            name='description_ca',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='themegroup',
            name='description_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='themegroup',
            name='description_es',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.CharField(max_length=80, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='area',
            name='description_ca',
            field=models.CharField(max_length=80, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='area',
            name='description_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='area',
            name='description_es',
            field=models.CharField(max_length=80, null=True, verbose_name='Description'),
        ),
    ]
