# Generated by Django 2.1.1 on 2018-12-10 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0007_area_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='themes.Area'),
        ),
    ]
