# Generated by Django 2.1.1 on 2018-12-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0009_auto_20181212_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementdetail',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='elementdetail',
            name='description_ca',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='elementdetail',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='elementdetail',
            name='description_es',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
