# Generated by Django 2.1.1 on 2018-12-19 10:45

from django.db import migrations
from django.db.models import F


def set_descriptions_from_name(apps, schema_editor):
    ElementDetail = apps.get_model('themes.ElementDetail')
    ElementDetail.objects.update(
        short_description=F('name'),
        short_description_ca=F('name'),
        short_description_en=F('name'),
        short_description_es=F('name')
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0010_auto_20181212_1659'),
    ]

    operations = [
        migrations.RunPython(set_descriptions_from_name, noop)
    ]
