# Generated by Django 2.1.1 on 2018-12-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0011_auto_20181219_1145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='elementdetail',
            unique_together={('element', 'short_description')},
        ),
    ]
