# Generated by Django 2.1.1 on 2018-12-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0012_auto_20181219_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementdetail',
            name='name',
        ),
    ]
