# Generated by Django 2.1.1 on 2019-01-02 15:30

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0013_remove_elementdetail_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('description', models.CharField(max_length=40, verbose_name='Description')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.ElementDetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
