# Generated by Django 2.1.1 on 2019-01-03 16:20

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0005_application'),
        ('themes', '0014_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationElementDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('favorited', models.BooleanField(default=False, verbose_name='Favorited')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_masters.Application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='elementdetail',
            name='applications',
            field=models.ManyToManyField(blank=True, through='themes.ApplicationElementDetail', to='iris_masters.Application'),
        ),
        migrations.AddField(
            model_name='applicationelementdetail',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.ElementDetail'),
        ),
    ]
