# Generated by Django 2.1.1 on 2019-01-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0016_auto_20190108_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementdetail',
            old_name='is_external',
            new_name='allow_external',
        ),
        migrations.AddField(
            model_name='elementdetail',
            name='allow_multiderivation_on_reassignment',
            field=models.BooleanField(default=False, verbose_name='Allow multiderivation on reassignment'),
        ),
        migrations.AddField(
            model_name='elementdetail',
            name='custom_answer',
            field=models.BooleanField(default=False, help_text='If true, the operator must write a custom answer for each record type of the theme.', verbose_name='Custom answer'),
        ),
        migrations.AddField(
            model_name='elementdetail',
            name='show_pda_resolution_time',
            field=models.BooleanField(default=False, verbose_name='Show PDA resolution time'),
        ),
    ]
