# Generated by Django 2.1.1 on 2019-01-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0017_auto_20190110_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementdetail',
            name='app_description_ca',
            field=models.CharField(blank=True, default='', help_text='Description shown on APP', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='elementdetail',
            name='app_description_en',
            field=models.CharField(blank=True, default='', help_text='Description shown on APP', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='elementdetail',
            name='app_description_es',
            field=models.CharField(blank=True, default='', help_text='Description shown on APP', max_length=80, null=True),
        ),
    ]
