# Generated by Django 2.1.1 on 2019-01-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0018_auto_20190110_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementdetail',
            name='app_description',
            field=models.CharField(default='', help_text='Description shown on APP', max_length=255),
        ),
        migrations.AlterField(
            model_name='elementdetail',
            name='app_description_ca',
            field=models.CharField(default='', help_text='Description shown on APP', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='elementdetail',
            name='app_description_en',
            field=models.CharField(default='', help_text='Description shown on APP', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='elementdetail',
            name='app_description_es',
            field=models.CharField(default='', help_text='Description shown on APP', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='elementdetail',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='elementdetail',
            name='description_ca',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='elementdetail',
            name='description_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='elementdetail',
            name='description_es',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='elementdetail',
            name='pda_description',
            field=models.CharField(blank=True, default='', help_text='Description shown on PDA', max_length=255),
        ),
    ]
