# Generated by Django 2.1.1 on 2019-01-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0020_auto_20190122_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementdetailapplication',
            name='application',
        ),
        migrations.RemoveField(
            model_name='elementdetailapplication',
            name='element_detail',
        ),
        migrations.RemoveField(
            model_name='elementdetail',
            name='app_description_ca',
        ),
        migrations.RemoveField(
            model_name='elementdetail',
            name='app_description_en',
        ),
        migrations.RemoveField(
            model_name='elementdetail',
            name='app_description_es',
        ),
        migrations.DeleteModel(
            name='ElementDetailApplication',
        ),
    ]
