# Generated by Django 2.1.1 on 2019-01-28 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0014_auto_20190128_1200'),
        ('themes', '0021_auto_20190122_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementdetail',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='iris_masters.Process', verbose_name='Process'),
        ),
    ]
