# Generated by Django 2.1.1 on 2019-01-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0022_elementdetail_process'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='keyword',
            index_together={('detail', 'description', 'enabled')},
        ),
    ]
