# Generated by Django 2.1.1 on 2019-01-30 16:48

from django.db import migrations, models
import django.utils.timezone
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0023_auto_20190129_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementdetailfeature',
            name='is_special',
        ),
        migrations.AddField(
            model_name='elementdetailfeature',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementdetailfeature',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AddField(
            model_name='elementdetailfeature',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Last update'),
        ),
        migrations.AddField(
            model_name='elementdetailfeature',
            name='user_id',
            field=iris_masters.models.UserIdField(default=' ', max_length=20, verbose_name='User ID'),
            preserve_default=False,
        ),
    ]
