# Generated by Django 2.1.1 on 2019-02-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0024_auto_20190130_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementdetail',
            name='app_description_ca',
            field=models.CharField(default='', help_text='Description shown on APP', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='elementdetail',
            name='app_description_en',
            field=models.CharField(default='', help_text='Description shown on APP', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='elementdetail',
            name='app_description_es',
            field=models.CharField(default='', help_text='Description shown on APP', max_length=255, null=True),
        ),
    ]
