# Generated by Django 2.1.1 on 2019-03-07 16:03

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0022_district'),
        ('profiles', '0003_auto_20190213_1226'),
        ('themes', '0027_auto_20190305_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiDerivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('derivation_type', models.CharField(blank=True, max_length=3, verbose_name='Derivation Type')),
                ('element_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.ElementDetail', verbose_name='Element Detail')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Profile')),
                ('record_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iris_masters.RecordState', verbose_name='Record State')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='multiderivation',
            unique_together={('element_detail', 'record_state', 'derivation_type')},
        ),
    ]
