# Generated by Django 2.1.1 on 2019-03-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0029_auto_20190308_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='favourite',
            field=models.BooleanField(default=False, verbose_name='Favourite'),
        ),
        migrations.AddField(
            model_name='element',
            name='favourite',
            field=models.BooleanField(default=False, verbose_name='Favourite'),
        ),
    ]
