# Generated by Django 2.1.1 on 2019-04-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0030_auto_20190314_1600'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='element',
            unique_together={('area', 'description', 'deleted')},
        ),
        migrations.RemoveField(
            model_name='elementdetail',
            name='response_channels',
        ),
        migrations.AlterUniqueTogether(
            name='elementdetail',
            unique_together={('element', 'short_description', 'deleted_at')},
        ),
    ]
