# Generated by Django 2.1.1 on 2019-04-03 16:03

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0029_resolutiontype'),
        ('themes', '0031_auto_20190401_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementDetailResponseChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('application', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='iris_masters.Application', verbose_name='Application')),
                ('elementdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.ElementDetail', verbose_name='Element Detail')),
                ('responsechannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iris_masters.ResponseChannel', verbose_name='Response Channel')),
            ],
            options={
                'db_table': 'themes_elementdetail_response_channels',
            },
        ),
        migrations.AddField(
            model_name='elementdetail',
            name='response_channels',
            field=models.ManyToManyField(blank=True, through='themes.ElementDetailResponseChannel', to='iris_masters.ResponseChannel'),
        ),
    ]
