# Generated by Django 2.1.1 on 2019-03-26 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0032_auto_20190403_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivationdistrict',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='multiderivation',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Group'),
        ),
    ]
