# Generated by Django 2.1.1 on 2019-05-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0035_auto_20190508_1148'),
        ('themes', '0034_auto_20190508_1143'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationelementdetail',
            unique_together={('detail', 'application', 'enabled')},
        ),
    ]
