# Generated by Django 2.1.1 on 2019-05-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0035_auto_20190508_1148'),
        ('profiles', '0017_auto_20190508_1143'),
        ('themes', '0035_auto_20190509_1801'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='multiderivation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='multiderivation',
            name='element_detail',
        ),
        migrations.RemoveField(
            model_name='multiderivation',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='multiderivation',
            name='record_state',
        ),
        migrations.RenameField(
            model_name='derivationdistrict',
            old_name='profile',
            new_name='group',
        ),
        migrations.DeleteModel(
            name='MultiDerivation',
        ),
    ]
