# Generated by Django 2.1.1 on 2019-05-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0038_derivationdistrict_record_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementdetailfeature',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='elementdetailfeature',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=100),
        ),
    ]
