# Generated by Django 2.1.1 on 2019-06-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0040_elementdetail_external_service'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationelementdetail',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='derivationdirect',
            unique_together=set(),
        ),
    ]
