# Generated by Django 2.1.1 on 2019-06-17 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20190613_0945'),
        ('themes', '0041_auto_20190604_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementDetailGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.ElementDetail', verbose_name='Element Detail')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Group', verbose_name='Group')),
            ],
        ),
    ]
