# Generated by Django 2.1.1 on 2019-07-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0042_elementdetailgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='themegroup',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
