# Generated by Django 2.1.1 on 2019-08-05 12:50

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.mixins
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0043_themegroup_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementDetailThemeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='Enabled')),
            ],
            options={
                'abstract': False,
            },
            bases=(iris_masters.mixins.CleanEnabledBase, models.Model),
        ),
        migrations.RemoveField(
            model_name='elementdetail',
            name='groups',
        ),
        migrations.AddField(
            model_name='elementdetailthemegroup',
            name='element_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.ElementDetail', verbose_name='Element Detail'),
        ),
        migrations.AddField(
            model_name='elementdetailthemegroup',
            name='theme_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.ThemeGroup', verbose_name='Theme Group'),
        ),
    ]
