# Generated by Django 2.1.1 on 2019-08-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0044_auto_20190805_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementdetail',
            name='groups',
            field=models.ManyToManyField(blank=True, through='themes.ElementDetailThemeGroup', to='themes.ThemeGroup'),
        ),
    ]
