# Generated by Django 2.1.1 on 2019-08-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0045_elementdetail_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementdetail',
            name='activation_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date from which the them will be visible', null=True, verbose_name='Activation Date'),
        ),
        migrations.AddField(
            model_name='elementdetail',
            name='active',
            field=models.BooleanField(db_index=True, default=True, help_text='If checked, the theme can be used in RecordCard creation', verbose_name='Active'),
        ),
    ]
