# Generated by Django 2.1.1 on 2019-08-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0046_auto_20190806_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementdetail',
            name='deleted',
            field=models.DateTimeField(blank=True, editable=False, help_text='Deletion date', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='elementdetail',
            unique_together={('element', 'short_description', 'deleted')},
        ),
    ]
