# Generated by Django 2.1.1 on 2019-08-27 09:46

from django.db import migrations


def update_deleted_element_detail(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ElementDetail = apps.get_model('themes', 'ElementDetail')
    for element_detail in ElementDetail.objects.all():
        element_detail.deleted = element_detail.deleted_at
        element_detail.save()


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0047_auto_20190827_1146'),
    ]

    operations = [
        migrations.RunPython(update_deleted_element_detail),
    ]
