# Generated by Django 2.1.1 on 2019-08-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0048_auto_20190827_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementdetail',
            name='deleted_at',
        ),
    ]
