# Generated by Django 2.1.1 on 2019-09-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0049_remove_elementdetail_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementdetail',
            name='visible',
            field=models.BooleanField(db_index=True, default=True, help_text='If checked, the theme can be shown in theme tree', verbose_name='Visible'),
        ),
        migrations.AddField(
            model_name='elementdetail',
            name='visible_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date from which the theme will be visible', null=True, verbose_name='Visible Date'),
        ),
        migrations.AlterField(
            model_name='elementdetail',
            name='activation_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date from which the theme will be active', null=True, verbose_name='Activation Date'),
        ),
    ]
