# Generated by Django 2.1.1 on 2019-10-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0050_auto_20190911_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last update'),
        ),
    ]
