# Generated by Django 2.1.1 on 2019-10-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0051_auto_20191010_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementdetail',
            name='external_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
