# Generated by Django 2.1.1 on 2019-12-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0053_auto_20191105_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementdetail',
            name='active',
            field=models.BooleanField(db_index=True, default=False, help_text='If checked, the theme can be used in RecordCard creation', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='elementdetail',
            name='visible',
            field=models.BooleanField(db_index=True, default=False, help_text='If checked, the theme can be shown in theme tree', verbose_name='Visible'),
        ),
    ]
