# Generated by Django 2.1.1 on 2019-12-14 10:30

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.mixins
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0051_auto_20191214_1130'),
        ('themes', '0054_auto_20191210_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfileElementDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='Enabled')),
            ],
            options={
                'abstract': False,
            },
            bases=(iris_masters.mixins.CleanEnabledBase, models.Model),
        ),
        migrations.AddField(
            model_name='elementdetail',
            name='average_close_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Average of days to close records of this theme.Null if it's not calculated", null=True, verbose_name='Average Close Days'),
        ),
        migrations.AddField(
            model_name='groupprofileelementdetail',
            name='element_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.ElementDetail'),
        ),
        migrations.AddField(
            model_name='groupprofileelementdetail',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='elementdetail',
            name='group_profiles',
            field=models.ManyToManyField(blank=True, through='themes.GroupProfileElementDetail', to='profiles.Group'),
        ),
    ]
