# Generated by Django 2.1.1 on 2020-01-08 15:46

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0053_auto_20191216_2053'),
        ('themes', '0055_auto_20191214_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementDetailDeleteRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('only_open', models.BooleanField(default=True, verbose_name='Only Open RecordCards')),
                ('process_finished', models.BooleanField(default=False, help_text='Shows if RecordCard details reassignations has finished correctly', verbose_name='Process finished')),
                ('deleted_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_details', to='themes.ElementDetail')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Group')),
                ('reasignation_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasignation_details', to='themes.ElementDetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
