# Generated by Django 2.1.1 on 2020-01-16 16:53

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.mixins
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0070_auto_20200110_1610'),
        ('profiles', '0055_auto_20200116_0919'),
        ('themes', '0057_auto_20200110_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivationPolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('polygon_code', models.CharField(max_length=100, verbose_name='Polygon Code')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='Enabled')),
                ('element_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.ElementDetail', verbose_name='Element Detail')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Group', verbose_name='Group')),
                ('record_state', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='iris_masters.RecordState', verbose_name='Record State')),
            ],
            options={
                'abstract': False,
            },
            bases=(iris_masters.mixins.CleanEnabledBase, models.Model),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('description', models.CharField(max_length=60, unique=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='derivationpolygon',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='themes.Zone', verbose_name='Zone'),
        ),
    ]
