# Generated by Django 2.1.1 on 2020-01-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0058_auto_20200116_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themegroup',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='themegroup',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='themegroup',
            name='description_es',
        ),
    ]
