# Generated by Django 2.1.1 on 2020-01-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0060_elementdetail_pend_commmunications'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementdetail',
            name='allow_english_lang',
            field=models.BooleanField(default=False, help_text='If checked, allows to select english as the language of the response', verbose_name='Allow english language'),
        ),
    ]
