# Generated by Django 2.1.1 on 2020-02-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0061_elementdetail_allow_english_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivationpolygon',
            name='district_mode',
            field=models.BooleanField(default=False),
        ),
    ]
