# Generated by Django 2.1.1 on 2020-02-18 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0071_auto_20200122_1203'),
        ('themes', '0063_auto_20200210_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementdetailgroup',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='iris_masters.District'),
        ),
    ]
