# Generated by Django 2.2 on 2021-11-22 13:41

from django.db import migrations
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0064_elementdetailgroup_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationelementdetail',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=36, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='area',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=36, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='derivationdirect',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=36, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='derivationdistrict',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=36, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='derivationpolygon',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=36, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='element',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=36, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='elementdetail',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=36, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='elementdetaildeleteregister',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=36, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='elementdetailfeature',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=36, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='elementdetailresponsechannel',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=36, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='elementdetailthemegroup',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=36, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='groupprofileelementdetail',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=36, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=36, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='themegroup',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=36, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=36, verbose_name='User ID'),
        ),
    ]
