# Generated by Django 2.2 on 2021-12-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0065_auto_20211122_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='codename',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Codename'),
        ),
    ]
