# Generated by Django 2.2 on 2021-12-15 09:36

from django.db import migrations


def set_codename(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Zone = apps.get_model('themes', 'Zone')
    for zone in Zone.objects.all():
        zone.codename = zone.description.replace(' ', '').lower()[:20]
        zone.save()


def undo(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0066_zone_codename'),
    ]

    operations = [
        migrations.RunPython(set_codename, undo)
    ]
