# Generated by Django 2.1.1 on 2019-12-18 16:10

from django.db import migrations, models
import iris_masters.models
import support_info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.IntegerField(choices=[(0, 'Frequently Asked Questions'), (1, 'Glossary'), (2, 'Documentation'), (3, 'Video'), (4, 'News')], db_index=True, verbose_name='Type')),
                ('category', models.IntegerField(blank=True, choices=[(0, 'Self Training Courses'), (1, 'General statistical DAIQ reports'), (2, 'User Manuals'), (3, 'Regulations'), (4, 'Links'), (5, 'Others')], help_text='Category for Documentation Type', null=True, verbose_name='Category')),
                ('file', models.FileField(blank=True, null=True, upload_to=support_info.models.support_info_path, verbose_name='File')),
                ('link', models.URLField(blank=True, help_text='Youtube link for Video Type or link for Document Type', verbose_name='Link')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
