# Generated by Django 2.1.1 on 2020-01-21 13:38

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import drf_chunked_upload.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support_info', '0002_auto_20200107_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportChunkedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=drf_chunked_upload.models.generate_filename)),
                ('filename', models.CharField(max_length=255)),
                ('offset', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Incomplete'), (2, 'Complete')], default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('support_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support_info.SupportInfo', verbose_name='Support Info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportchunkedfile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-completed_at', '-status', '-created_at'),
            },
        ),
    ]
