# Generated by Django 2.2 on 2022-02-01 09:20

from django.db import migrations
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('support_info', '0006_auto_20211202_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportinfo',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
    ]
