# Generated by Django 2.1.1 on 2019-01-15 13:49

from django.db import migrations, models
import iris_masters.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('via_type', models.CharField(max_length=35, verbose_name='Via Type')),
                ('official_street_name', models.CharField(blank=True, max_length=120, verbose_name='Official Street Name')),
                ('street', models.CharField(max_length=120, verbose_name='Street')),
                ('street2', models.CharField(blank=True, max_length=60, verbose_name='Street 2')),
                ('nexus', models.BooleanField(default=False, verbose_name='Nexus')),
                ('neighborhood', models.CharField(blank=True, max_length=80, verbose_name='Neighborhood')),
                ('neighborhood_b', models.CharField(blank=True, max_length=80, verbose_name='Neighborhood B')),
                ('neighborhood_id', models.CharField(blank=True, max_length=10, verbose_name='Neighborhood ID')),
                ('district', models.CharField(blank=True, max_length=80, verbose_name='District')),
                ('statistical_sector', models.CharField(blank=True, max_length=80, verbose_name='Statistical Sector')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('geocode_validation', models.CharField(blank=True, max_length=60, verbose_name='Geocode Validation')),
                ('geocode_district_id', models.CharField(blank=True, max_length=10, verbose_name='Geocodeo District ID')),
                ('research_zone', models.CharField(blank=True, max_length=10, verbose_name='Research Zone')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='Floor')),
                ('door', models.CharField(blank=True, max_length=20, verbose_name='Door')),
                ('letter', models.CharField(blank=True, max_length=3, verbose_name='Letter')),
                ('coordinate_x', models.FloatField(blank=True, null=True, verbose_name='Coordinate X')),
                ('coordinate_y', models.FloatField(blank=True, null=True, verbose_name='Coordinate Y')),
                ('coordinate_utm_x', models.FloatField(blank=True, null=True, verbose_name='Coordinate UTM X')),
                ('coordinate_utm_y', models.FloatField(blank=True, null=True, verbose_name='Coordinate UTM Y')),
                ('latitude', models.CharField(blank=True, max_length=20, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=20, verbose_name='Longitude')),
                ('xetrs89a', models.FloatField(blank=True, null=True, verbose_name='Xetrs89a')),
                ('yetrs89a', models.FloatField(blank=True, null=True, verbose_name='Yetrs89a')),
                ('numbering_type', models.BooleanField(default=False, verbose_name='Numbering type')),
                ('temp_error', models.TextField(blank=True, verbose_name='Temp error')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
