# Generated by Django 2.1.1 on 2019-01-23 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0002_auto_20190123_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='communication_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='iris_masters.CommunicationMedia', verbose_name='Communication Media'),
        ),
    ]
