# Generated by Django 2.1.1 on 2019-01-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0003_auto_20190123_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='mib_code',
            field=models.PositiveIntegerField(null=True, verbose_name='MIB Code'),
        ),
        migrations.AlterField(
            model_name='recordcard',
            name='communication_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='iris_masters.CommunicationMedia', verbose_name='Communication Media'),
        ),
        migrations.AlterField(
            model_name='socialentity',
            name='mib_code',
            field=models.PositiveIntegerField(null=True, verbose_name='MIB Code'),
        ),
    ]
