# Generated by Django 2.1.1 on 2019-01-24 15:28

from django.db import migrations
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0004_auto_20190124_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcard',
            name='responsible_profile',
            field=iris_masters.models.UserIdField(max_length=20, verbose_name='Responsible profile'),
        ),
    ]
