# Generated by Django 2.1.1 on 2019-01-28 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0005_auto_20190124_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcard',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='iris_masters.Process', verbose_name='Process'),
        ),
        migrations.AlterField(
            model_name='request',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='iris_masters.Application', verbose_name='Application'),
        ),
    ]
