# Generated by Django 2.1.1 on 2019-01-29 11:02

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0006_auto_20190128_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcard',
            name='communication_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='iris_masters.CommunicationMedia', verbose_name='Communication Media'),
        ),
        migrations.AlterField(
            model_name='recordcard',
            name='responsible_profile',
            field=iris_masters.models.UserIdField(blank=True, max_length=20, null=True, verbose_name='Responsible profile'),
        ),
    ]
