# Generated by Django 2.1.1 on 2019-01-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0007_auto_20190129_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordcard',
            name='auxiliary_ca',
        ),
        migrations.RemoveField(
            model_name='recordcard',
            name='auxiliary_en',
        ),
        migrations.RemoveField(
            model_name='recordcard',
            name='auxiliary_es',
        ),
        migrations.RemoveField(
            model_name='recordcard',
            name='communication_media_detail_ca',
        ),
        migrations.RemoveField(
            model_name='recordcard',
            name='communication_media_detail_en',
        ),
        migrations.RemoveField(
            model_name='recordcard',
            name='communication_media_detail_es',
        ),
        migrations.RemoveField(
            model_name='recordcard',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='recordcard',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='recordcard',
            name='description_es',
        ),
    ]
