# Generated by Django 2.1.1 on 2019-01-31 08:43

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20190130_1748'),
        ('record_cards', '0008_auto_20190130_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordCardFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature', verbose_name='Feature')),
                ('record_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_cards.RecordCard', verbose_name='RecordCard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecordCardSpecialFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Feature', verbose_name='Feature')),
                ('record_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_cards.RecordCard', verbose_name='RecordCard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recordcard',
            name='features',
            field=models.ManyToManyField(blank=True, through='record_cards.RecordCardFeatures', to='features.Feature'),
        ),
        migrations.AddField(
            model_name='recordcard',
            name='special_features',
            field=models.ManyToManyField(blank=True, related_name='special_features', through='record_cards.RecordCardSpecialFeatures', to='features.Feature'),
        ),
    ]
