# Generated by Django 2.1.1 on 2019-01-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0009_auto_20190131_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcard',
            name='normalized_record_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Normalized Record Id'),
        ),
    ]
