# Generated by Django 2.1.1 on 2019-02-04 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0010_auto_20190131_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcard',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='record_cards.Request', verbose_name='Request'),
        ),
    ]
