# Generated by Django 2.1.1 on 2019-02-04 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0011_auto_20190204_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcard',
            name='ci_date',
            field=models.DateField(blank=True, null=True, verbose_name='CI Date'),
        ),
        migrations.AlterField(
            model_name='recordcard',
            name='closing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Closing date'),
        ),
        migrations.AlterField(
            model_name='recordcard',
            name='communication_media_date',
            field=models.DateField(blank=True, null=True, verbose_name='Communication Media Date'),
        ),
        migrations.AlterField(
            model_name='recordcard',
            name='create_profile',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Create profile'),
        ),
        migrations.AlterField(
            model_name='recordcard',
            name='email_external_derivation',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email external derivation'),
        ),
        migrations.AlterField(
            model_name='recordcard',
            name='multi_complaint',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Multi complaint'),
        ),
        migrations.AlterField(
            model_name='recordcard',
            name='notify_quality',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Notify quality'),
        ),
        migrations.AlterField(
            model_name='recordcard',
            name='start_date_process',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date Process'),
        ),
        migrations.AlterField(
            model_name='recordcard',
            name='ubication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='record_cards.Ubication', verbose_name='Ubication'),
        ),
    ]
