# Generated by Django 2.1.1 on 2019-02-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0012_auto_20190204_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcard',
            name='ans_limit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ANS limit date'),
        ),
    ]
