# Generated by Django 2.1.1 on 2019-02-05 14:29

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0018_parameter_visible'),
        ('themes', '0024_auto_20190130_1748'),
        ('record_cards', '0013_recordcard_ans_limit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordCardHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('description', models.TextField(verbose_name='Description')),
                ('responsible_profile', iris_masters.models.UserIdField(blank=True, max_length=20, null=True, verbose_name='Responsible profile')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('mayorship', models.BooleanField(default=False, verbose_name='Mayorship')),
                ('normalized_record_id', models.CharField(blank=True, max_length=20, verbose_name='Normalized Record Id')),
                ('alarm', models.BooleanField(default=False, verbose_name='Alarm')),
                ('auxiliary', models.CharField(blank=True, max_length=40, verbose_name='Auxiliary')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Closing date')),
                ('ans_overcome', models.PositiveIntegerField(default=0, verbose_name='ANS overcome')),
                ('ans_limit_date', models.DateTimeField(blank=True, null=True, verbose_name='ANS limit date')),
                ('communication_media_date', models.DateField(blank=True, null=True, verbose_name='Communication Media Date')),
                ('communication_media_detail', models.CharField(blank=True, max_length=100, verbose_name='Communication Media Detail')),
                ('record_parent_claimed', models.CharField(blank=True, max_length=30, verbose_name='Record Parent Claimed')),
                ('reassignment_not_allowed', models.BooleanField(default=False, verbose_name='Reassignment not Allowed')),
                ('urgent', models.BooleanField(default=False, verbose_name='Urgent')),
                ('page_origin', models.CharField(blank=True, max_length=100, verbose_name='Page origin')),
                ('email_external_derivation', models.EmailField(blank=True, max_length=254, verbose_name='Email external derivation')),
                ('user_displayed', models.CharField(max_length=20, verbose_name='User displayed')),
                ('historicized', models.CharField(default='N', max_length=3, verbose_name='Historicized')),
                ('allow_multiderivation', models.BooleanField(default=True, verbose_name='Allow Multiderivation')),
                ('start_date_process', models.DateField(blank=True, null=True, verbose_name='Start Date Process')),
                ('similar_process', models.BooleanField(default=False, verbose_name='Similar process')),
                ('response_state', models.CharField(blank=True, max_length=40, verbose_name='Response State')),
                ('notify_quality', models.PositiveIntegerField(blank=True, null=True, verbose_name='Notify quality')),
                ('create_profile', models.PositiveIntegerField(blank=True, null=True, verbose_name='Create profile')),
                ('multi_complaint', models.PositiveIntegerField(blank=True, null=True, verbose_name='Multi complaint')),
                ('lopd', models.NullBooleanField(verbose_name='LOPD')),
                ('applicant_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iris_masters.ApplicantType', verbose_name='Applicant Type')),
                ('communication_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='iris_masters.CommunicationMedia', verbose_name='Communication Media')),
                ('element_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='themes.ElementDetail', verbose_name='Element Detail')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='iris_masters.Process', verbose_name='Process')),
                ('record_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_cards.RecordCard', verbose_name='Record Card')),
                ('record_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iris_masters.RecordState', verbose_name='Record State')),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iris_masters.RecordType', verbose_name='Record Type')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='record_cards.Request', verbose_name='Request')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iris_masters.Support')),
                ('ubication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='record_cards.Ubication', verbose_name='Ubication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
