# Generated by Django 2.1.1 on 2019-02-07 08:47

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0018_parameter_visible'),
        ('record_cards', '0014_recordcardhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='iris_masters.Reason', verbose_name='Reason')),
                ('record_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='record_cards.RecordCard', verbose_name='Record Card')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
