# Generated by Django 2.1.1 on 2019-02-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0016_auto_20190213_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubication',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='ubication',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='ubication',
            name='numbering_type',
            field=models.CharField(default=False, max_length=1, verbose_name='Numbering type'),
        ),
    ]
