# Generated by Django 2.1.1 on 2019-02-13 16:06

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0020_auto_20190213_1256'),
        ('record_cards', '0017_auto_20190213_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordCardResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('address_mobile_email', models.CharField(blank=True, max_length=200, verbose_name='Address, Mobile or Email')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Number')),
                ('municipality', models.CharField(blank=True, max_length=80, verbose_name='Municipality')),
                ('province', models.CharField(blank=True, max_length=80, verbose_name='Province')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Postal code')),
                ('answered', models.BooleanField(default=False, verbose_name='Answered')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('via_type', models.CharField(blank=True, max_length=35, verbose_name='Via Type')),
                ('via_name', models.CharField(blank=True, max_length=100, verbose_name='Via Name')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='Floor')),
                ('door', models.CharField(blank=True, max_length=20, verbose_name='Door')),
                ('stair', models.CharField(blank=True, max_length=20, verbose_name='Stair')),
                ('correct_response_data', models.BooleanField(default=True, verbose_name='Correct Response Data')),
                ('record_card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='record_cards.RecordCard', verbose_name='Record Card')),
                ('response_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iris_masters.ResponseChannel', verbose_name='Response Channel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
