# Generated by Django 2.1.1 on 2019-02-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20190213_1241'),
        ('record_cards', '0019_auto_20190213_1735'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recordcardfeatures',
            unique_together={('record_card', 'feature')},
        ),
        migrations.AlterUniqueTogether(
            name='recordcardspecialfeatures',
            unique_together={('record_card', 'feature')},
        ),
    ]
