# Generated by Django 2.1.1 on 2019-02-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0020_auto_20190219_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcardfeatures',
            name='value',
            field=models.CharField(blank=True, max_length=200, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='recordcardspecialfeatures',
            name='value',
            field=models.CharField(blank=True, max_length=200, verbose_name='Value'),
        ),
    ]
