# Generated by Django 2.1.1 on 2019-02-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0021_auto_20190219_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcard',
            name='normalized_record_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Normalized Record Id'),
        ),
    ]
