# Generated by Django 2.1.1 on 2019-03-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0023_auto_20190225_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcardhistory',
            name='ans_overcome',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='ANS overcome'),
        ),
    ]
