# Generated by Django 2.1.1 on 2019-03-07 09:54

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0022_district'),
        ('record_cards', '0025_auto_20190305_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordCardResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_person_incharge', models.CharField(max_length=100, verbose_name='Service or person in charge')),
                ('resolution_type', models.CharField(max_length=100, verbose_name='Resolution Type')),
                ('resolution_date', models.DateField(verbose_name='Resolution Date')),
                ('appointment_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Appointment Date Time')),
                ('appointment_person', models.CharField(blank=True, max_length=100, verbose_name='Appointment Person')),
                ('record_card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='record_cards.RecordCard', verbose_name='Record Card')),
            ],
        ),
        migrations.CreateModel(
            name='RecordCardTextResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('response', models.TextField(verbose_name='Response')),
                ('send_date', models.DateField(verbose_name='Send Date')),
                ('text_date', models.DateField(auto_now_add=True, verbose_name='Text date')),
                ('record_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record_cards.RecordCard', verbose_name='Record Card')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='Close Date')),
                ('visual_user', models.CharField(blank=True, max_length=50, verbose_name='Visual User')),
                ('element_detail_modified', models.BooleanField(default=False, verbose_name='Theme modified')),
                ('main_record_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_record_card', to='record_cards.RecordCard', verbose_name='Record Card')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iris_masters.RecordState', verbose_name='State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('task', models.CharField(choices=[('Planning', 'Planning'), ('Resolution', 'Resolution')], max_length=20, verbose_name='Task')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record_cards.Workflow', verbose_name='Workflow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recordcard',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='record_cards.Workflow', verbose_name='Workflow'),
        ),
        migrations.AddField(
            model_name='recordcardhistory',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='record_cards.Workflow', verbose_name='Workflow'),
        ),
    ]
