# Generated by Django 2.1.1 on 2019-03-13 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0026_auto_20190307_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='language',
            field=models.CharField(choices=[('es', 'Castilian'), ('en', 'English'), ('ca', 'Catalan')], default='ca', max_length=2, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='sex',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1, verbose_name='Sex'),
        ),
        migrations.AddField(
            model_name='socialentity',
            name='language',
            field=models.CharField(choices=[('es', 'Castilian'), ('en', 'English'), ('ca', 'Catalan')], default='ca', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='birth_year',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Birth Year'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='district',
            field=models.CharField(max_length=80, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='socialentity',
            name='district',
            field=models.CharField(max_length=80, verbose_name='District'),
        ),
    ]
