# Generated by Django 2.1.1 on 2019-03-13 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0027_auto_20190313_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='iris_masters.District', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='socialentity',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='iris_masters.District', verbose_name='District'),
        ),
    ]
