# Generated by Django 2.1.1 on 2019-03-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0030_auto_20190318_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordcardresolution',
            name='appointment_date_time',
        ),
        migrations.RemoveField(
            model_name='recordcardresolution',
            name='appointment_person',
        ),
        migrations.AddField(
            model_name='recordcardresolution',
            name='is_appointment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recordcardresolution',
            name='resolution_date',
            field=models.DateTimeField(null=True, verbose_name='Resolution Date'),
        ),
        migrations.AlterField(
            model_name='recordcardresolution',
            name='service_person_incharge',
            field=models.CharField(blank=True, max_length=100, verbose_name='Service or person in charge'),
        ),
    ]
