# Generated by Django 2.1.1 on 2019-04-09 11:54

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0032_recordfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordCardBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('blocked', models.BooleanField(default=True, verbose_name='Blocked')),
                ('record_card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='record_cards.RecordCard', verbose_name='RecordCard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
