# Generated by Django 2.1.1 on 2019-04-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0034_auto_20190409_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='dni',
            field=models.CharField(max_length=15, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='socialentity',
            name='cif',
            field=models.CharField(max_length=15, verbose_name='CIF'),
        ),
        migrations.AlterUniqueTogether(
            name='citizen',
            unique_together={('dni', 'enabled')},
        ),
        migrations.AlterUniqueTogether(
            name='socialentity',
            unique_together={('cif', 'enabled')},
        ),
    ]
