# Generated by Django 2.1.1 on 2019-03-27 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20190326_1442'),
        ('record_cards', '0035_auto_20190409_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.Group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='workflowcomment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.Group', verbose_name='Group'),
        ),
    ]
