# Generated by Django 2.1.1 on 2019-03-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0036_auto_20190327_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='dni',
            field=models.CharField(max_length=15, verbose_name='DNI'),
        ),
    ]
