# Generated by Django 2.1.1 on 2019-04-15 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0038_recordcardstatehistory_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citizen',
            unique_together=set(),
        ),
    ]
