# Generated by Django 2.1.1 on 2019-04-12 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0039_auto_20190415_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='doc_type',
        ),
    ]
