# Generated by Django 2.1.1 on 2019-04-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0040_remove_citizen_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='doc_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'NIF'), (1, 'NIE'), (2, 'PASS')], default=0, verbose_name='Document Type'),
        ),
    ]
