# Generated by Django 2.1.1 on 2019-04-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0034_auto_20190412_1159'),
        ('record_cards', '0041_citizen_doc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_profile', models.CharField(blank=True, max_length=100, verbose_name='Service or person in charge')),
                ('start_date_process', models.DateTimeField(null=True, verbose_name='Start Date Process')),
                ('action_required', models.BooleanField(default=True)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='record_cards.Workflow', verbose_name='Workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_person_incharge', models.CharField(blank=True, max_length=100, verbose_name='Service or person in charge')),
                ('resolution_date', models.DateTimeField(null=True, verbose_name='Resolution Date')),
                ('is_appointment', models.BooleanField(default=False)),
                ('resolution_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iris_masters.ResolutionType', verbose_name='Resolution Type')),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='record_cards.Workflow', verbose_name='Workflow')),
            ],
        ),
        migrations.RemoveField(
            model_name='recordcardresolution',
            name='record_card',
        ),
        migrations.RemoveField(
            model_name='recordcardresolution',
            name='resolution_type',
        ),
        migrations.DeleteModel(
            name='RecordCardResolution',
        ),
    ]
