# Generated by Django 2.1.1 on 2019-04-15 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0043_auto_20190503_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcard',
            name='responsible_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.Group', verbose_name='Responsible profile'),
        ),
    ]
