# Generated by Django 2.1.1 on 2019-05-03 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0044_auto_20190415_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcardhistory',
            name='responsible_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.Group', verbose_name='Responsible profile'),
        ),
    ]
