# Generated by Django 2.1.1 on 2019-05-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0045_auto_20190503_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowcomment',
            name='task',
            field=models.CharField(choices=[('p', 'Planning'), ('r', 'Resolution')], max_length=20, verbose_name='Task'),
        ),
    ]
