# Generated by Django 2.1.1 on 2019-04-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0047_recordcardreasignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcard',
            name='reasigned',
            field=models.BooleanField(default=False, help_text='Shows if RecordCard has been manually reasigned or not', verbose_name='Reasigned'),
        ),
    ]
