# Generated by Django 2.1.1 on 2019-05-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0049_auto_20190508_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcardstatehistory',
            name='automatic',
            field=models.BooleanField(default=False, help_text='Set to true if the state change has been done automatically', verbose_name='Automatic'),
        ),
    ]
