# Generated by Django 2.1.1 on 2019-05-10 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0050_recordcardstatehistory_automatic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcard',
            name='is_multirecord',
            field=models.BooleanField(default=False, verbose_name='Is MultiRecord'),
        ),
        migrations.AddField(
            model_name='recordcard',
            name='multirecord_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='record_cards.RecordCard', verbose_name='MultiRecord From'),
        ),
    ]
