# Generated by Django 2.1.1 on 2019-05-13 14:55

import django.core.validators
from django.db import migrations, models
import main.api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0051_auto_20190510_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='birth_year',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), main.api.validators.MaxYearValidator()], verbose_name='Birth Year'),
        ),
    ]
