# Generated by Django 2.1.1 on 2019-06-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0052_auto_20190513_1655'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recordcardfeatures',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='recordcardspecialfeatures',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='socialentity',
            unique_together=set(),
        ),
    ]
