# Generated by Django 2.1.1 on 2019-06-12 10:40

from django.db import migrations


def set_is_theme_feature(apps, schema_editor):
    RecordCardFeatures = apps.get_model('record_cards', 'RecordCardFeatures')
    RecordCardSpecialFeatures = apps.get_model('record_cards', 'RecordCardSpecialFeatures')

    for model in [RecordCardFeatures, RecordCardSpecialFeatures]:
        for record_card_feature in model.objects.all():
            theme_features = record_card_feature.record_card.element_detail.feature_configs.all().values_list(
                'feature_id', flat=True)
            record_card_feature.is_theme_feature = True if record_card_feature.feature_id in theme_features else False
            record_card_feature.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0054_auto_20190612_1240'),
    ]

    operations = [
        migrations.RunPython(set_is_theme_feature, noop),
    ]
