# Generated by Django 2.1.1 on 2019-05-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0055_auto_20190612_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcard',
            name='possible_similar',
            field=models.ManyToManyField(related_name='_recordcard_possible_similar_+', to='record_cards.RecordCard', verbose_name='Possible Similar Records'),
        ),
    ]
