# Generated by Django 2.1.1 on 2019-06-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0056_recordcard_possible_similar'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcard',
            name='possible_similar_records',
            field=models.BooleanField(default=False, verbose_name='Possible Similar Records'),
        ),
    ]
