# Generated by Django 2.1.1 on 2019-06-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0057_recordcard_possible_similar_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcard',
            name='applicant_response',
            field=models.BooleanField(default=False, verbose_name='Applicant Response'),
        ),
        migrations.AddField(
            model_name='recordcard',
            name='pend_applicant_response',
            field=models.BooleanField(default=False, verbose_name='Pend Applicant Response'),
        ),
        migrations.AddField(
            model_name='recordcard',
            name='response_time_expired',
            field=models.BooleanField(default=False, verbose_name='Response Time Expired'),
        ),
    ]
