# Generated by Django 2.1.1 on 2019-07-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0059_auto_20190710_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='recordcardreasignation',
            name='reason',
        ),
    ]
