# Generated by Django 2.1.1 on 2019-07-24 15:50
from datetime import datetime

from django.db import migrations, models
import django.db.models.deletion


DEFAULT_REASON_ID = 3


def create_default_reason(apps, schema_editor):
    """
    We need a default reason in order to add the Reason foreign key field.
    :param apps:
    :param schema_editor:
    :return:
    """
    Reason = apps.get_model('iris_masters.Reason')
    Reason.objects.get_or_create(id=DEFAULT_REASON_ID, defaults={
        "description": u"Reassignació per error en classificació temàtica",
        "created_at": datetime(2005, 3, 22),
        "deleted": None,
        "user_id": "IRIS",
        "reason_type": '2'
    })


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0046_auto_20190724_1732'),
        ('record_cards', '0060_auto_20190724_1735'),
    ]

    operations = [
        migrations.RunPython(create_default_reason, noop),
        migrations.AddField(
            model_name='comment',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='iris_masters.Reason', verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='recordcardreasignation',
            name='reason',
            field=models.ForeignKey(default=DEFAULT_REASON_ID, on_delete=django.db.models.deletion.PROTECT, to='iris_masters.Reason', verbose_name='Reason'),
            preserve_default=False,
        ),
    ]
