# Generated by Django 2.1.1 on 2019-09-03 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0061_auto_20190724_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcard',
            name='claimed_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claim', to='record_cards.RecordCard', verbose_name='Claim From'),
        ),
        migrations.AddField(
            model_name='recordcard',
            name='claims_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of claims'),
        ),
    ]
