# Generated by Django 2.1.1 on 2019-09-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0062_auto_20190903_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcard',
            name='cancel_department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Department on cancelation'),
        ),
        migrations.AddField(
            model_name='recordcard',
            name='creation_department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Department on creation'),
        ),
    ]
