# Generated by Django 2.1.1 on 2019-10-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0064_auto_20190919_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation date'),
        ),
    ]
