# Generated by Django 2.1.1 on 2019-10-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0065_auto_20191003_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcard',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closing date'),
        ),
    ]
