# Generated by Django 2.1.1 on 2019-10-14 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0051_auto_20191010_1201'),
        ('record_cards', '0066_auto_20191007_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcard',
            name='original_element_detail',
            field=models.ForeignKey(editable=False, help_text='Field for traceability and report purpose. Not edit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='original_theme', to='themes.ElementDetail', verbose_name='Element Detail'),
        ),
    ]
