# Generated by Django 2.1.1 on 2019-10-15 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0067_recordcard_original_element_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantresponse',
            name='response_lang',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('ca', 'Catalan')], default='ca', max_length=2, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='recordcardresponse',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('ca', 'Catalan')], default='ca', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='applicantresponse',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='record_cards.Applicant', verbose_name='Applicant'),
        ),
    ]
