# Generated by Django 2.1.1 on 2019-10-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0068_auto_20191015_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantresponse',
            name='language',
        ),
    ]
