# Generated by Django 2.1.1 on 2019-10-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0069_remove_applicantresponse_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantresponse',
            old_name='response_lang',
            new_name='language',
        ),
    ]
