# Generated by Django 2.1.1 on 2019-10-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0070_auto_20191015_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresponse',
            name='email',
            field=models.EmailField(blank=True, max_length=30, unique=True, verbose_name='Email'),
        ),
    ]
