# Generated by Django 2.1.1 on 2019-10-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0072_auto_20191017_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubication',
            name='street',
            field=models.CharField(blank=True, max_length=120, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='ubication',
            name='via_type',
            field=models.CharField(blank=True, max_length=35, verbose_name='Via Type'),
        ),
    ]
