# Generated by Django 2.1.1 on 2019-10-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_auto_20191011_1035'),
        ('record_cards', '0073_auto_20191017_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcard',
            name='creation_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create_records', to='profiles.Group', verbose_name='Creation group'),
        ),
    ]
