# Generated by Django 2.1.1 on 2019-10-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0074_recordcard_creation_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresponse',
            name='email',
            field=models.EmailField(blank=True, max_length=30, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='applicantresponse',
            name='mobile_number',
            field=models.CharField(max_length=30, verbose_name='Mobile Number'),
        ),
    ]
