# Generated by Django 2.1.1 on 2019-11-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0076_recordcard_cancel_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcard',
            name='response_worked',
            field=models.BooleanField(default=False, verbose_name='Response worked'),
        ),
    ]
