# Generated by Django 2.1.1 on 2019-11-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0077_recordcard_response_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordcard',
            name='response_worked',
        ),
        migrations.AddField(
            model_name='recordcardresponse',
            name='worked',
            field=models.BooleanField(default=False, verbose_name='Worked'),
        ),
    ]
