# Generated by Django 2.1.1 on 2019-11-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0078_auto_20191106_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordcardresponse',
            name='worked',
        ),
        migrations.AddField(
            model_name='recordcardtextresponse',
            name='worked',
            field=models.BooleanField(default=False, verbose_name='Worked'),
        ),
    ]
