# Generated by Django 2.1.1 on 2019-11-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0079_auto_20191107_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcard',
            name='user_displayed',
            field=models.CharField(blank=True, max_length=20, verbose_name='User displayed'),
        ),
    ]
