# Generated by Django 2.1.1 on 2019-11-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0063_auto_20191115_1233'),
        ('record_cards', '0082_internaloperator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaloperator',
            name='document',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Internal operator document'),
        ),
        migrations.AlterUniqueTogether(
            name='internaloperator',
            unique_together={('document', 'applicant_type', 'input_channel')},
        ),
    ]
