# Generated by Django 2.1.1 on 2019-11-18 08:26

from django.db import migrations, models
import record_cards.models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0083_auto_20191115_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfile',
            name='file',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to=record_cards.models.record_files_path, verbose_name='Record File'),
        ),
    ]
