# Generated by Django 2.1.1 on 2019-11-18 14:50

from django.db import migrations, models
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0084_auto_20191118_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresponse',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=30, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='applicantresponse',
            name='mobile_number',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='applicantresponse',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='applicantresponse',
            name='street',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='dni',
            field=models.CharField(db_index=True, max_length=15, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='first_surname',
            field=models.CharField(db_index=True, max_length=60, verbose_name='First Surname'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='full_normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Full normal name'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='name',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='second_surname',
            field=models.CharField(blank=True, db_index=True, max_length=60, verbose_name='Second Surname'),
        ),
        migrations.AlterField(
            model_name='recordcard',
            name='alarm',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Alarm'),
        ),
        migrations.AlterField(
            model_name='recordcard',
            name='citizen_alarm',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Citizen alarm'),
        ),
        migrations.AlterField(
            model_name='recordcard',
            name='closing_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Closing date'),
        ),
        migrations.AlterField(
            model_name='recordcard',
            name='creation_department',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Department on creation'),
        ),
        migrations.AlterField(
            model_name='recordcard',
            name='mayorship',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Mayorship'),
        ),
        migrations.AlterField(
            model_name='recordcard',
            name='user_id',
            field=iris_masters.models.UserIdField(db_index=True, max_length=20, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='socialentity',
            name='cif',
            field=models.CharField(db_index=True, max_length=15, verbose_name='CIF'),
        ),
        migrations.AlterField(
            model_name='socialentity',
            name='social_reason',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Social Reason'),
        ),
        migrations.AlterField(
            model_name='ubication',
            name='neighborhood',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Neighborhood'),
        ),
        migrations.AlterField(
            model_name='ubication',
            name='street',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='ubication',
            name='street2',
            field=models.CharField(blank=True, db_index=True, max_length=60, verbose_name='Street 2'),
        ),
    ]
