# Generated by Django 2.1.1 on 2019-11-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0085_auto_20191118_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AddIndex(
            model_name='recordcard',
            index=models.Index(fields=['-created_at'], name='record_card_created_ae9648_idx'),
        ),
    ]
