# Generated by Django 2.1.1 on 2019-11-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0086_auto_20191122_1501'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recordcard',
            index=models.Index(fields=['created_at'], name='record_card_created_c3013b_idx'),
        ),
    ]
