# Generated by Django 2.1.1 on 2019-12-04 07:59

from django.db import migrations
from django.db.models import Subquery, OuterRef


def group_soft_delete(apps, schema_editor):
    RecordCard = apps.get_model('record_cards', 'RecordCard')
    Workflow = apps.get_model('record_cards', 'Workflow')
    RecordCard.objects.filter(closing_date__isnull=True).select_related('workflow').update(
        closing_date=Subquery(Workflow.objects.filter(pk=OuterRef('workflow_id')).values('close_date')[:1])
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0087_auto_20191128_1259'),
    ]

    operations = [
        migrations.RunPython(group_soft_delete, noop)
    ]
