# Generated by Django 2.1.1 on 2019-12-05 11:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0088_auto_20191204_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordcardblock',
            options={'ordering': ('-expire_time',)},
        ),
        migrations.RemoveField(
            model_name='recordcardblock',
            name='blocked',
        ),
        migrations.AddField(
            model_name='recordcardblock',
            name='expire_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Block expire time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recordcardblock',
            name='record_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record_cards.RecordCard', verbose_name='RecordCard'),
        ),
        migrations.AddIndex(
            model_name='recordcardblock',
            index=models.Index(fields=['-expire_time'], name='record_card_expire__75eb06_idx'),
        ),
    ]
