# Generated by Django 2.1.1 on 2019-12-10 15:25

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0089_auto_20191205_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordCardAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_user', iris_masters.models.UserIdField(blank=True, max_length=20, verbose_name='Validation User')),
                ('planif_user', iris_masters.models.UserIdField(blank=True, max_length=20, verbose_name='Planification User')),
                ('resol_user', iris_masters.models.UserIdField(blank=True, max_length=20, verbose_name='Resolution User')),
                ('resol_comment', models.TextField(blank=True, verbose_name='Resolution Comment')),
                ('close_user', iris_masters.models.UserIdField(blank=True, max_length=20, verbose_name='Closing User')),
                ('record_card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='record_cards.RecordCard', verbose_name='Record Card')),
            ],
        ),
    ]
