# Generated by Django 2.1.1 on 2019-12-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0090_recordcardaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthindicator',
            name='entries',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Record Entries'),
        ),
    ]
