# Generated by Django 2.1.1 on 2019-12-14 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0091_monthindicator_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='record_cards.Applicant', verbose_name='Applicant'),
        ),
    ]
