# Generated by Django 2.1.1 on 2019-12-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0092_auto_20191214_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcardtextresponse',
            name='worked',
            field=models.CharField(blank=True, max_length=1, verbose_name='Worked'),
        ),
    ]
