# Generated by Django 2.1.1 on 2019-12-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0093_auto_20191224_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordchunkedfile',
            name='file_type',
            field=models.IntegerField(choices=[(0, 'From Record Creation'), (1, 'From Record Detail'), (2, 'From Record Communications'), (3, 'From Public Web')], default=0, verbose_name='File Type'),
        ),
        migrations.AddField(
            model_name='recordfile',
            name='file_type',
            field=models.IntegerField(choices=[(0, 'From Record Creation'), (1, 'From Record Detail'), (2, 'From Record Communications'), (3, 'From Public Web')], default=0, verbose_name='File Type'),
        ),
    ]
