# Generated by Django 2.1.1 on 2020-01-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0094_auto_20191224_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcard',
            name='organization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Organization'),
        ),
    ]
