# Generated by Django 2.1.1 on 2020-01-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0096_auto_20200108_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcardtextresponse',
            name='worked',
            field=models.CharField(blank=True, choices=[('t', 'Response worked'), ('p', 'Template Changed'), ('o', 'Others')], max_length=1, verbose_name='Worked'),
        ),
    ]
