# Generated by Django 2.1.1 on 2020-01-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0097_auto_20200108_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubication',
            name='polygon_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Polygon Code'),
        ),
    ]
