# Generated by Django 2.1.1 on 2020-01-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0098_ubication_polygon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcard',
            name='notify_quality',
            field=models.BooleanField(blank=True, null=True, verbose_name='Notify quality'),
        ),
    ]
