# Generated by Django 2.1.1 on 2020-01-22 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0099_auto_20200121_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internaloperator',
            options={'ordering': ('document',)},
        ),
        migrations.AlterField(
            model_name='recordchunkedfile',
            name='record_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_cards.RecordCard', verbose_name='Record Card'),
        ),
    ]
