# Generated by Django 2.1.1 on 2020-01-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0100_auto_20200122_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcard',
            name='ans_limit_nearexpire',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ANS limit near expire'),
        ),
    ]
