# Generated by Django 2.1.1 on 2020-01-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0102_auto_20200122_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcard',
            name='allow_multiderivation',
            field=models.BooleanField(default=False, verbose_name='Allow Multiderivation'),
        ),
    ]
