# Generated by Django 2.1.1 on 2020-01-23 10:13

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.mixins
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0104_ubication_stair'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordCardTextResponseFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='Enabled')),
                ('record_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_cards.RecordFile')),
                ('text_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_cards.RecordCardTextResponse')),
            ],
            options={
                'abstract': False,
            },
            bases=(iris_masters.mixins.CleanEnabledBase, models.Model),
        ),
        migrations.AddField(
            model_name='recordcardtextresponse',
            name='record_files',
            field=models.ManyToManyField(blank=True, through='record_cards.RecordCardTextResponseFiles', to='record_cards.RecordFile'),
        ),
    ]
