# Generated by Django 2.1.1 on 2020-01-27 09:35

from django.db import migrations
from django.utils import timezone


def disabled_to_deleted_registers(apps, schema_editor):
    # We can"t import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Citizen = apps.get_model("record_cards", "Citizen")
    Citizen.objects.filter(enabled=False).update(deleted=timezone.now())
    SocialEntity = apps.get_model("record_cards", "SocialEntity")
    SocialEntity.objects.filter(enabled=False).update(deleted=timezone.now())
    Applicant = apps.get_model("record_cards", "Applicant")
    Applicant.objects.filter(enabled=False).update(deleted=timezone.now())


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('record_cards', '0106_auto_20200127_1035'),
    ]

    operations = [
        migrations.RunPython(disabled_to_deleted_registers, noop),
    ]
