# Generated by Django 2.1.1 on 2020-02-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0113_auto_20200224_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordcard',
            name='create_profile',
        ),
        migrations.RemoveField(
            model_name='recordcardhistory',
            name='create_profile',
        ),
    ]
