# Generated by Django 2.1.1 on 2020-03-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0116_auto_20200306_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantresponse',
            name='treatment',
        ),
    ]
