# Generated by Django 2.1.1 on 2020-03-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0117_remove_applicantresponse_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcard',
            name='citizen_web_alarm',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Citizen web alarm'),
        ),
    ]
