# Generated by Django 2.1.1 on 2020-04-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0118_recordcard_citizen_web_alarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordcard',
            name='ans_overcome',
        ),
        migrations.RemoveField(
            model_name='recordcardhistory',
            name='ans_overcome',
        ),
    ]
