# Generated by Django 2.1.1 on 2021-02-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0122_auto_20201027_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubication',
            name='official_street_name',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Official Street Name'),
        ),
    ]
