# Generated by Django 2.1.1 on 2021-03-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0123_auto_20210215_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcard',
            name='normalized_record_id',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Normalized Record Id'),
        ),
    ]
