# Generated by Django 2.1.1 on 2021-03-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0125_auto_20210311_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcardresponse',
            name='address_mobile_email',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Address, Mobile or Email'),
        ),
    ]
