# Generated by Django 2.1.1 on 2021-03-22 16:07

from django.db import migrations
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0126_auto_20210319_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcardaudit',
            name='close_user',
            field=iris_masters.models.UserIdField(blank=True, db_index=True, max_length=20, verbose_name='Closing User'),
        ),
        migrations.AlterField(
            model_name='recordcardaudit',
            name='planif_user',
            field=iris_masters.models.UserIdField(blank=True, db_index=True, max_length=20, verbose_name='Planification User'),
        ),
        migrations.AlterField(
            model_name='recordcardaudit',
            name='resol_user',
            field=iris_masters.models.UserIdField(blank=True, db_index=True, max_length=20, verbose_name='Resolution User'),
        ),
        migrations.AlterField(
            model_name='recordcardaudit',
            name='validation_user',
            field=iris_masters.models.UserIdField(blank=True, db_index=True, max_length=20, verbose_name='Validation User'),
        ),
    ]
