# Generated by Django 2.2 on 2021-11-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '130_function_cursor_recordcard_reasignation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordcardspecialfeaturesaux',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='recordcardspecialfeaturesaux',
            name='record_card',
        ),
        migrations.AlterModelTable(
            name='recordcardfeaturesaux',
            table='record_cards_recordcardfeaturesauxtmp',
        ),
        migrations.AlterModelTable(
            name='recordcardspecialfeaturesaux',
            table='record_cards_recordcardspecialfeaturesauxtmp',
        ),
        migrations.AlterModelTable(
            name='recordcardfeatures',
            table='record_cards_recordcardfeaturesaux',
        ),
        migrations.AlterModelTable(
            name='recordcardspecialfeatures',
            table='record_cards_recordcardspecialfeaturesaux',
        ),
        migrations.DeleteModel(
            name='RecordCardFeaturesAux',
        ),
        migrations.DeleteModel(
            name='RecordCardSpecialFeaturesAux',
        ),
    ]
