# Generated by Django 2.2 on 2022-01-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0133_auto_20211202_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('ca', 'Catalan')], default='es', max_length=2, verbose_name='Language'),
        ),
    ]
