# Generated by Django 2.2 on 2022-01-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0134_auto_20220121_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresponse',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('gl', 'Galician')], default='es', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('gl', 'Galician')], default='es', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='recordcardresponse',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('gl', 'Galician')], default='es', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='socialentity',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('gl', 'Galician')], default='es', max_length=2, verbose_name='Language'),
        ),
    ]
