# Generated by Django 2.2 on 2022-02-01 09:20

from django.db import migrations
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0135_auto_20220126_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='applicantresponse',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='extendedgeocodeubication',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='internaloperator',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='recordcard',
            name='user_displayed',
            field=iris_masters.models.UserIdField(blank=True, max_length=291, verbose_name='User displayed'),
        ),
        migrations.AlterField(
            model_name='recordcard',
            name='user_id',
            field=iris_masters.models.UserIdField(db_index=True, max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='recordcardaudit',
            name='close_user',
            field=iris_masters.models.UserIdField(blank=True, db_index=True, max_length=291, verbose_name='Closing User'),
        ),
        migrations.AlterField(
            model_name='recordcardaudit',
            name='planif_user',
            field=iris_masters.models.UserIdField(blank=True, db_index=True, max_length=291, verbose_name='Planification User'),
        ),
        migrations.AlterField(
            model_name='recordcardaudit',
            name='resol_user',
            field=iris_masters.models.UserIdField(blank=True, db_index=True, max_length=291, verbose_name='Resolution User'),
        ),
        migrations.AlterField(
            model_name='recordcardaudit',
            name='validation_user',
            field=iris_masters.models.UserIdField(blank=True, db_index=True, max_length=291, verbose_name='Validation User'),
        ),
        migrations.AlterField(
            model_name='recordcardblock',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='recordcardfeatures',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='recordcardhistory',
            name='user_displayed',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User displayed'),
        ),
        migrations.AlterField(
            model_name='recordcardhistory',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='recordcardreasignation',
            name='user_id',
            field=iris_masters.models.UserIdField(db_index=True, max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='recordcardresponse',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='recordcardspecialfeatures',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='recordcardstatehistory',
            name='user_id',
            field=iris_masters.models.UserIdField(db_index=True, max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='recordcardtextresponse',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='recordcardtextresponsefiles',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='recordfile',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='socialentity',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='ubication',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='workflowcomment',
            name='user_id',
            field=iris_masters.models.UserIdField(max_length=291, verbose_name='User ID'),
        ),
    ]
