# Generated by Django 2.2.28 on 2023-02-27 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0136_auto_20220201_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowResolutionExtraFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_date_end', models.DateTimeField(null=True, verbose_name='Resolution Date End')),
                ('ubication_end', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubication_end', to='record_cards.Ubication', verbose_name='Ubication end')),
                ('ubication_start', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubication_start', to='record_cards.Ubication', verbose_name='Ubication start')),
                ('workflow_resolution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='record_cards.WorkflowResolution', verbose_name='Workflow')),
            ],
        ),
    ]
