# Generated by Django 2.2.28 on 2023-09-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0138_auto_20230227_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowcomment',
            options={'ordering': ('-created_at',)},
        ),
    ]
