# Generated by Django 2.1.1 on 2019-01-30 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Description')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValuesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Last update')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Description')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AddField(
            model_name='feature',
            name='explanatory_text',
            field=models.TextField(blank=True, verbose_name='Explanatory Text'),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Special'),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_value_type',
            field=models.BooleanField(default=False, verbose_name='Value Types'),
        ),
        migrations.AddField(
            model_name='feature',
            name='mask_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mask ID'),
        ),
        migrations.AddField(
            model_name='feature',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Last update'),
        ),
        migrations.AddField(
            model_name='feature',
            name='user_id',
            field=iris_masters.models.UserIdField(default=' ', max_length=20, verbose_name='User ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.CharField(max_length=100, unique=False, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='values',
            name='values_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='features.ValuesType'),
        ),
        migrations.AddField(
            model_name='feature',
            name='values_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='features.ValuesType'),
        ),
    ]
