# Generated by Django 2.1.1 on 2019-02-13 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20190213_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.IntegerField(choices=[(1, 'Any Character'), (2, 'Only Letters'), (3, 'Any Number'), (4, 'Integer'), (5, 'Phone Number (9 digits)'), (6, 'Postal Code (5 digits)'), (7, 'Date Format DD/MM/YYYY'), (8, 'Hour Format HH:MM')], primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('description', models.CharField(max_length=15, verbose_name='Description')),
                ('description_es', models.CharField(max_length=15, null=True, verbose_name='Description')),
                ('description_ca', models.CharField(max_length=15, null=True, verbose_name='Description')),
                ('description_en', models.CharField(max_length=15, null=True, verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='feature',
            name='mask_id',
        ),
        migrations.AddField(
            model_name='feature',
            name='description_ca',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='feature',
            name='description_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='feature',
            name='description_es',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='feature',
            name='explanatory_text_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Explanatory Text'),
        ),
        migrations.AddField(
            model_name='feature',
            name='explanatory_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Explanatory Text'),
        ),
        migrations.AddField(
            model_name='feature',
            name='explanatory_text_es',
            field=models.TextField(blank=True, null=True, verbose_name='Explanatory Text'),
        ),
        migrations.AddField(
            model_name='values',
            name='description_ca',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='values',
            name='description_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='values',
            name='description_es',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='valuestype',
            name='description_ca',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='valuestype',
            name='description_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='valuestype',
            name='description_es',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='feature',
            name='mask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='features.Mask'),
        ),
    ]
