# Generated by Django 2.1.1 on 2019-03-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20190213_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='description_ca',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
    ]
