# Generated by Django 2.1.1 on 2019-03-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_auto_20190305_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='type',
            field=models.CharField(choices=[('Text', 'Text'), ('Number', 'Number'), ('Date', 'Date'), ('Time', 'Time')], default='Number', max_length=15, verbose_name='Type'),
        ),
    ]
