# Generated by Django 2.1.1 on 2019-04-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_mask_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='values',
            name='description_ca',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='values',
            name='description_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='values',
            name='description_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='valuestype',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='valuestype',
            name='description_ca',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='valuestype',
            name='description_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='valuestype',
            name='description_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.RemoveField(
            model_name='feature',
            name='is_value_type',
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together={('description', 'enabled', 'values_type')},
        ),
        migrations.AlterUniqueTogether(
            name='values',
            unique_together={('description', 'enabled', 'values_type')},
        ),
        migrations.AlterUniqueTogether(
            name='valuestype',
            unique_together={('description', 'enabled')},
        ),
    ]
