# Generated by Django 2.1.1 on 2019-05-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_auto_20190405_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='values',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='valuestype',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
    ]
