# Generated by Django 2.1.1 on 2019-06-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_auto_20190507_1604'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='values',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='valuestype',
            unique_together=set(),
        ),
    ]
