# Generated by Django 2.1.1 on 2019-09-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_auto_20190725_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='editable_for_citizen',
            field=models.BooleanField(default=True, help_text='This feature will be filled with automatic values.'),
        ),
        migrations.AddField(
            model_name='feature',
            name='visible_for_citizen',
            field=models.BooleanField(default=True, help_text="This feature won't be show to citizens, only in backoffice."),
        ),
    ]
