# Generated by Django 2.1.1 on 2020-01-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0013_auto_20200110_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='values',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='values',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
