# Generated by Django 2.1.1 on 2020-01-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0014_auto_20200116_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('description',)},
        ),
        migrations.AlterModelOptions(
            name='valuestype',
            options={'ordering': ('description',)},
        ),
    ]
