# Generated by Django 2.1.1 on 2020-02-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0015_auto_20200121_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='codename',
            field=models.CharField(blank=True, default='', help_text='GET parameter for integrations', max_length=40),
        ),
    ]
