# Generated by Django 2.1.1 on 2021-01-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0016_feature_codename'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='codename_iris',
            field=models.CharField(blank=True, default='', help_text='GET parameter for backoffice GET integration', max_length=40),
        ),
    ]
