# Generated by Django 2.1.1 on 2019-05-02 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('record_cards', '0041_citizen_doc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_cards.RecordCard')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.Survey')),
            ],
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='survey_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.SurveyAnswer'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='surveys.Survey'),
        ),
    ]
