# Generated by Django 2.1.1 on 2019-05-03 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record_cards', '0041_citizen_doc_type'),
        ('surveys', '0002_auto_20190502_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='require_reason_from',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='surveys.Survey'),
        ),
        migrations.AlterField(
            model_name='questionreason',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='surveys.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyanswer',
            unique_together={('record_card', 'survey')},
        ),
    ]
