# Generated by Django 2.1.1 on 2019-05-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20190503_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionreason',
            name='text_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionreason',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionreason',
            name='text_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='title_ca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='title_es',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
