# Generated by Django 2.1.1 on 2021-04-27 12:32

from datetime import datetime

from django.db import migrations


def add_created_to_surveys(apps, schema_editor):
    add_created_at(apps, "Survey")
    add_created_at(apps, "Question")
    add_created_at(apps, "QuestionReason")
    add_created_at(apps, "SurveyAnswer")
    add_created_at(apps, "QuestionAnswer")


def add_created_at(apps, model_name):
    model_class = apps.get_model('surveys', model_name)
    for register in model_class.objects.all():
        # Set created_at as the day of IRIS2 launch
        register.created_at = datetime(2021, 2, 6)
        register.save()


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20210427_1428'),
    ]

    operations = [
        migrations.RunPython(add_created_to_surveys)
    ]
