# Generated by Django 2.2 on 2022-01-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_add_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text_ca',
            new_name='text_gl',
        ),
        migrations.RenameField(
            model_name='questionreason',
            old_name='text_ca',
            new_name='text_gl',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='title_ca',
            new_name='title_gl',
        ),
    ]
