# Generated by Django 2.1.1 on 2019-02-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_applicationprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='applicationprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update'),
        ),
    ]
