# Generated by Django 2.1.1 on 2019-03-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190213_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(max_length=40, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description_ca',
            field=models.CharField(max_length=40, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description_es',
            field=models.CharField(max_length=40, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.URLField(blank=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_pending_delivery',
            field=models.DateField(blank=True, null=True, verbose_name='Last pending delivery'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='letter_template_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Letter template id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pending_shipping_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pending shipping days'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sector',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='service_line',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Service line'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='signature',
            field=models.URLField(blank=True, verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='validate_thematic_tree',
            field=models.NullBooleanField(verbose_name='Validate Thematic Tree'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('description', 'profile_ctrl_user_id', 'enabled')},
        ),
    ]
