# Generated by Django 2.1.1 on 2019-03-26 10:41

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('themes', '0033_auto_20190326_1141'),
        ('profiles', '0005_usergroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Group',
        ),
    ]
