# Generated by Django 2.1.1 on 2019-03-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20190326_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='group',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='group',
            name='description_es',
        ),
    ]
