# Generated by Django 2.1.1 on 2019-03-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20190326_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='citizen_nd',
            field=models.BooleanField(default=False, verbose_name='Citizen ND'),
        ),
    ]
