# Generated by Django 2.1.1 on 2019-04-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20190327_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Is AnonymousGroup'),
        ),
    ]
