# Generated by Django 2.1.1 on 2019-04-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris_masters', '0033_support_allow_nd'),
        ('profiles', '0011_auto_20190411_1012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationProfile',
            new_name='ApplicationGroup',
        ),
    ]
