# Generated by Django 2.1.1 on 2019-04-25 10:23

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20190411_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupReassignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('origin_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.Group', verbose_name='Origin Group')),
                ('reasign_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reasignations', to='profiles.Group', verbose_name='Reasign Group')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='groupreassignation',
            unique_together={('origin_group', 'reasign_group', 'enabled')},
        ),
    ]
