# Generated by Django 2.1.1 on 2019-04-29 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20190425_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAIRGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
