# Generated by Django 2.1.1 on 2019-04-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_dairgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_ambit',
            field=models.BooleanField(default=False, verbose_name='Is Ambit'),
        ),
    ]
