# Generated by Django 2.1.1 on 2019-05-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20190507_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationgroup',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='group',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='groupinputchannel',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='groupreassignation',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Enabled'),
        ),
    ]
