# Generated by Django 2.1.1 on 2019-06-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20190603_0947'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupinputchannel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='groupreassignation',
            unique_together=set(),
        ),
    ]
