# Generated by Django 2.1.1 on 2019-06-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20190604_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='signature',
            field=models.CharField(blank=True, max_length=200, verbose_name='Signature'),
        ),
    ]
