# Generated by Django 2.1.1 on 2019-07-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20190613_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('codename', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60)),
                ('codename', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions', to='profiles.PermissionCategory'),
        ),
    ]
