# Generated by Django 2.1.1 on 2019-07-02 13:22

from django.db import migrations, models
import django.utils.timezone
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20190702_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update'),
        ),
        migrations.AddField(
            model_name='permission',
            name='user_id',
            field=iris_masters.models.UserIdField(default='', max_length=20, verbose_name='User ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permissioncategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permissioncategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update'),
        ),
        migrations.AddField(
            model_name='permissioncategory',
            name='user_id',
            field=iris_masters.models.UserIdField(default='', max_length=20, verbose_name='User ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=iris_masters.models.UserIdField(default='', max_length=20, verbose_name='User ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='groups', through='profiles.GroupProfiles', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permissions',
            field=models.ManyToManyField(related_name='profiles', through='profiles.ProfilePermissions', to='profiles.Permission'),
        ),
    ]
