# Generated by Django 2.1.1 on 2019-07-08 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_auto_20190702_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofiles',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_profiles', to='profiles.Profile'),
        ),
    ]
