# Generated by Django 2.1.1 on 2019-07-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20190708_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
