# Generated by Django 2.1.1 on 2019-08-02 10:03

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.mixins
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_profile_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCanReassign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='Enabled')),
            ],
            options={
                'abstract': False,
            },
            bases=(iris_masters.mixins.CleanEnabledBase, models.Model),
        ),
        migrations.AddField(
            model_name='group',
            name='reassignments',
            field=models.ManyToManyField(blank=True, through='profiles.GroupReassignation', to='profiles.Group'),
        ),
        migrations.AddField(
            model_name='groupcanreassign',
            name='can_reasign_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='can_reasing_groups', to='profiles.Group', verbose_name='Can Reasign to Group'),
        ),
        migrations.AddField(
            model_name='groupcanreassign',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.Group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='group',
            name='can_reasign_groups',
            field=models.ManyToManyField(blank=True, related_name='groups_can_reasign', through='profiles.GroupCanReassign', to='profiles.Group'),
        ),
    ]
