# Generated by Django 2.1.1 on 2019-08-05 08:48

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_auto_20190802_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDeleteRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('only_open', models.BooleanField(default=True, verbose_name='Only Open RecordCards')),
                ('process_finished', models.BooleanField(default=False, help_text='Shows if recordCard reassignations and derivations reassignations has finished correctly', verbose_name='Process finished')),
                ('deleted_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Group')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_delete_groups', to='profiles.Group')),
                ('reasignation_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_groups', to='profiles.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
