# Generated by Django 2.1.1 on 2019-09-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_groupdeleteregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
