# Generated by Django 2.1.1 on 2019-09-18 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_auto_20190918_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='notifications_emails',
            field=models.TextField(blank=True, help_text='List of emails (separated by commas) to send notifications', verbose_name='Notifications emails list'),
        ),
        migrations.AddField(
            model_name='group',
            name='pend_records',
            field=models.BooleanField(default=False, help_text='Send notifications for pending records', verbose_name='Pending records'),
        ),
        migrations.AddField(
            model_name='group',
            name='pend_records_freq',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Pending records frequency (days)'),
        ),
        migrations.AddField(
            model_name='group',
            name='records_allocation',
            field=models.BooleanField(default=False, help_text='Send notifications for records allocation', verbose_name='Records Allocation'),
        ),
        migrations.AddField(
            model_name='group',
            name='records_next_expire',
            field=models.BooleanField(default=False, help_text='Send notifications for records next to expire', verbose_name='Records Next to expire'),
        ),
        migrations.AddField(
            model_name='group',
            name='records_next_expire_freq',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Records Next to expire frequency (days)'),
        ),
    ]
