# Generated by Django 2.1.1 on 2019-09-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_auto_20190919_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pend_records_notif_date',
            field=models.DateField(blank=True, help_text='Last day pending records  has been notified', null=True, verbose_name='Pending records last notify date'),
        ),
        migrations.AddField(
            model_name='group',
            name='records_next_expire_notif_date',
            field=models.DateField(blank=True, help_text='Last day records next to expire has been notified', null=True, verbose_name='Records next to expire last notify date'),
        ),
    ]
