# Generated by Django 2.1.1 on 2019-10-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_auto_20190919_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dairgroup',
            name='group',
        ),
        migrations.DeleteModel(
            name='DAIRGroup',
        ),
    ]
