# Generated by Django 2.1.1 on 2019-10-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0038_auto_20191003_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcanreassign',
            name='can_reasign_group',
        ),
        migrations.RemoveField(
            model_name='groupcanreassign',
            name='group',
        ),
        migrations.RemoveField(
            model_name='group',
            name='can_reasign_groups',
        ),
        migrations.DeleteModel(
            name='GroupCanReassign',
        ),
    ]
