# Generated by Django 2.1.1 on 2019-10-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_auto_20191011_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_plate',
            field=models.CharField(blank=True, help_text='Group Plate', max_length=30),
        ),
    ]
