# Generated by Django 2.1.1 on 2019-10-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0040_group_group_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_plate',
            field=models.CharField(blank=True, help_text='Group Plate', max_length=100),
        ),
    ]
