# Generated by Django 2.1.1 on 2019-10-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0041_auto_20191025_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_plate',
            field=models.CharField(blank=True, db_index=True, help_text='Group Plate', max_length=100),
        ),
    ]
