# Generated by Django 2.1.1 on 2019-11-15 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0044_auto_20191114_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='letter_template_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iris_masters.LetterTemplate', verbose_name='Letter template id'),
        ),
    ]
