# Generated by Django 2.1.1 on 2019-11-28 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0047_auto_20191030_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Group', verbose_name='Group')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserGroup', verbose_name='User Group')),
            ],
        ),
    ]
