# Generated by Django 2.1.1 on 2019-11-28 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0048_accesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='ambit_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinator', to='profiles.Group'),
        ),
    ]
