# Generated by Django 2.1.1 on 2019-12-11 19:02

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.mixins
import iris_masters.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0049_group_ambit_coordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='Enabled')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Group')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserGroup', verbose_name='User Group')),
            ],
            options={
                'abstract': False,
            },
            bases=(iris_masters.mixins.CleanEnabledBase, models.Model),
        ),
    ]
