# Generated by Django 2.1.1 on 2019-12-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0050_profileusergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='profiles', through='profiles.ProfileUserGroup', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='profileusergroup',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Profile'),
        ),
    ]
