# Generated by Django 2.1.1 on 2019-12-16 19:53

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0052_auto_20191216_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=profiles.models.group_icons_path, verbose_name='Icon'),
        ),
    ]
