# Generated by Django 2.1.1 on 2020-01-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0053_auto_20191216_2053'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('description', 'deleted')},
        ),
    ]
