# Generated by Django 2.1.1 on 2020-01-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0054_auto_20200110_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='permissioncategory',
            name='codename',
            field=models.CharField(max_length=20),
        ),
    ]
