# Generated by Django 2.1.1 on 2020-01-22 10:05


from django.db import migrations


def usernames_upper(apps, schema_editor):
    UserGroup = apps.get_model("profiles", "UserGroup")

    for user_group in UserGroup.objects.all():
        user_group.user.username = user_group.user.username.upper()
        user_group.user.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0056_auto_20200121_1601'),
    ]

    operations = [
        migrations.RunPython(usernames_upper, noop),
    ]
