# Generated by Django 2.1.1 on 2020-01-27 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0057_auto_20200122_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pend_communication',
            field=models.BooleanField(default=False, help_text='Send notifications for records with pending communications', verbose_name='Records with pending communications'),
        ),
        migrations.AddField(
            model_name='group',
            name='pend_communication_freq',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Pending communications records frequency (days)'),
        ),
        migrations.AddField(
            model_name='group',
            name='pend_communication_notif_date',
            field=models.DateField(blank=True, help_text='Last day records with pending communications has been notified', null=True, verbose_name='Records with pending communications last notify date'),
        ),
    ]
