# Generated by Django 2.1.1 on 2020-02-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0058_auto_20200127_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tree_levels',
            field=models.SmallIntegerField(default=1, verbose_name='Number of levels above for seeing the tree'),
        ),
    ]
