# Generated by Django 2.1.1 on 2020-03-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0059_group_tree_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='pending_shipping_days',
        ),
    ]
