# Generated by Django 2.2.28 on 2023-03-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0063_auto_20220201_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_mobile',
            field=models.BooleanField(default=False, verbose_name='Is Mobile'),
        ),
    ]
