# Generated by Django 2.2.28 on 2023-09-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0064_group_is_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileusergroup',
            name='prefered_language',
            field=models.CharField(choices=[('ES', 'Español'), ('GL', 'Galego')], default='GL', max_length=2, verbose_name='prefered_language'),
        ),
    ]
