# Generated by Django 2.2 on 2021-12-14 08:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('themes', '0065_auto_20211122_1441'),
        ('iris_masters', '0078_auto_20211122_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCategory',
            fields=[
                ('zone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='themes.Zone')),
                ('name', models.CharField(max_length=20, verbose_name='Category description')),
                ('ubication_field', models.CharField(blank=True, default='', help_text='Ubication field to fill with the bound result.', max_length=30, verbose_name='Record Card field')),
            ],
            options={
                'abstract': False,
            },
            bases=('themes.zone',),
        ),
        migrations.CreateModel(
            name='DistrictBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=25829)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iris_masters.District')),
            ],
        ),
        migrations.CreateModel(
            name='AreaBounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('codename', models.CharField(max_length=3)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=25829)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bounds', to='geo.AreaCategory')),
            ],
        ),
    ]
