# Generated by Django 2.1.1 on 2019-06-28 09:30

from django.db import migrations, models
import django.db.models.deletion
import iris_masters.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0022_auto_20190613_0945'),
        ('iris_masters', '0042_auto_20190617_1617'),
        ('record_cards', '0057_recordcard_possible_similar_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('type', models.IntegerField(choices=[(0, 'Internal conversation'), (1, 'External conversation'), (2, 'Applicant conversation')], default=0, verbose_name='Conversation Type')),
                ('is_opened', models.BooleanField(default=True, help_text='Conversation is opened', verbose_name='Is opened')),
                ('external_email', models.EmailField(blank=True, help_text="External email involved on conversation, if it's External Type", max_length=254, verbose_name='External email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='Enabled')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='communications.Conversation', verbose_name='Conversation')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.Group', verbose_name='Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationUnreadMessagesGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_messages', models.IntegerField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='communications.Conversation', verbose_name='Conversation')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.Group', verbose_name='Group')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', iris_masters.models.UserIdField(max_length=20, verbose_name='User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('text', models.TextField(verbose_name='Text Message')),
                ('hash', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Message hash')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='communications.Conversation', verbose_name='Conversation')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.Group', verbose_name='Group')),
                ('record_state', models.ForeignKey(help_text='State of the RecordCard on the creation of the message', on_delete=django.db.models.deletion.PROTECT, to='iris_masters.RecordState')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='groups_involved',
            field=models.ManyToManyField(blank=True, help_text="Groups involved on conversation, if it's Internal Type", through='communications.ConversationGroup', to='profiles.Group', verbose_name='Groups involved'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='record_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record_cards.RecordCard', verbose_name='RecordCard'),
        ),
    ]
