# Generated by Django 2.1.1 on 2019-06-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='Messages is answered'),
        ),
    ]
