# Generated by Django 2.1.1 on 2019-07-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_message_is_answered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at',)},
        ),
    ]
