# Generated by Django 2.1.1 on 2019-07-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20190613_0945'),
        ('communications', '0003_auto_20190701_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='creation_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creation_group', to='profiles.Group', verbose_name='Creation Group'),
        ),
    ]
