# Generated by Django 2.1.1 on 2019-08-01 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_conversation_creation_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationunreadmessagesgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationunreadmessagesgroup',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
