# Generated by Django 2.1.1 on 2019-11-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_auto_20190801_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='require_answer',
            field=models.BooleanField(default=True, help_text='Indicates if an answer is expected', verbose_name='Require answer'),
        ),
    ]
