# Generated by Django 2.1.1 on 2020-09-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualScheduleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
                ('task', models.CharField(db_index=True, max_length=200)),
                ('created_by', models.CharField(max_length=20)),
                ('cancelled_by', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('s', 'Scheduled'),
                                                     ('c', 'Cancelled'),
                                                     ('e', 'Error enqueuing, please reschedule')],
                                            db_index=True, default='S', max_length=1)),
                ('scheduled_date', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
