# Generated by Django 2.1.1 on 2020-09-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_task_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manualschedulelog',
            options={'ordering': ('-scheduled_date',)},
        ),
        migrations.AlterField(
            model_name='manualschedulelog',
            name='json',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='manualschedulelog',
            name='status',
            field=models.CharField(choices=[('s', 'Scheduled'),
                                            ('c', 'Cancelled'),
                                            ('e', 'Error enqueuing, please reschedule'),
                                            ('r', 'Ready')], db_index=True, default='s', max_length=1),
        ),
    ]
